chore: Bump pydantic to ^2.3.0
ToucanToco/toucan-connectors pull request #1272
Opened 2023-09-11 09:42 UTC by lukapeschke

2023-09-13 14:08 UTC, PrettyWood requested changes
Sinon top 👍 Content du refacto pour le kwarg dans `__init_subclass__`
C'est encore plus clean

2023-09-13 14:08 UTC, PrettyWood commented on tests/soap/test_soap.py
> +    assert form['$defs']['method']['const'] == 'fake_func'
J'aurais proposé de changer [`DEFAULT_REF_TEMPLATE`](https://docs.pydantic.dev/latest/api/json_schema/#pydantic.json_schema.DEFAULT_REF_TEMPLATE) pour changer le moins de tests possibles

2023-09-14 10:00 UTC, lukapeschke commented on tests/soap/test_soap.py
> +    assert form['$defs']['method']['const'] == 'fake_func'
Je viens de tester avec `ref_template='#/definitions/{model}'`, et les definitions restent malgré tout dans la clé `$defs`. Seule leur référence change. Exemple:

```python
from enum import StrEnum
import json

from pydantic import BaseModel


class E(StrEnum):
    one = "one"
    two = "two"


class A(BaseModel):
    e: E


print(json.dumps(A.model_json_schema(), indent=2))
print(json.dumps(A.model_json_schema(ref_template="#/definitions/{model}"), indent=2))
```

Donne

```javascript
{
  "$defs": {
    "E": {
      "enum": [
        "one",
        "two"
      ],
      "title": "E",
      "type": "string"
    }
  },
  "properties": {
    "e": {
      "$ref": "#/$defs/E"
    }
  },
  "required": [
    "e"
  ],
  "title": "A",
  "type": "object"
}
{
  "$defs": {
    "E": {
      "enum": [
        "one",
        "two"
      ],
      "title": "E",
      "type": "string"
    }
  },
  "properties": {
    "e": {
      "$ref": "#/definitions/E"
    }
  },
  "required": [
    "e"
  ],
  "title": "A",
  "type": "object"
}
```

2023-09-14 10:01 UTC, lukapeschke commented on tests/soap/test_soap.py
> +    assert form['$defs']['method']['const'] == 'fake_func'
Je viens de tester avec `ref_template='#/definitions/{model}'`, et les definitions restent malgré tout dans la clé `$defs`. Seule leur référence change. Exemple:

```python
from enum import StrEnum
import json

from pydantic import BaseModel


class E(StrEnum):
    one = "one"
    two = "two"


class A(BaseModel):
    e: E


print(json.dumps(A.model_json_schema(), indent=2))
print(json.dumps(A.model_json_schema(ref_template="#/definitions/{model}"), indent=2))
```

Donne

```javascript
{
  "$defs": {
    "E": {
      "enum": [
        "one",
        "two"
      ],
      "title": "E",
      "type": "string"
    }
  },
  "properties": {
    "e": {
      "$ref": "#/$defs/E"
    }
  },
  "required": [
    "e"
  ],
  "title": "A",
  "type": "object"
}
{
  "$defs": {
    "E": {
      "enum": [
        "one",
        "two"
      ],
      "title": "E",
      "type": "string"
    }
  },
  "properties": {
    "e": {
      "$ref": "#/definitions/E"
    }
  },
  "required": [
    "e"
  ],
  "title": "A",
  "type": "object"
}
```

2023-09-14 10:01 UTC, lukapeschke commented on tests/soap/test_soap.py
> +    assert form['$defs']['method']['const'] == 'fake_func'
Je viens de tester avec `ref_template='#/definitions/{model}'`, et les definitions restent malgré tout dans la clé `$defs`. Seule leur référence change. Exemple:

```python
from enum import StrEnum
import json

from pydantic import BaseModel


class E(StrEnum):
    one = "one"
    two = "two"


class A(BaseModel):
    e: E


print(json.dumps(A.model_json_schema(), indent=2))
print(json.dumps(A.model_json_schema(ref_template="#/definitions/{model}"), indent=2))
```

Donne

```javascript
{
  "$defs": {
    "E": {
      "enum": [
        "one",
        "two"
      ],
      "title": "E",
      "type": "string"
    }
  },
  "properties": {
    "e": {
      "$ref": "#/$defs/E"
    }
  },
  "required": [
    "e"
  ],
  "title": "A",
  "type": "object"
}
{
  "$defs": {
    "E": {
      "enum": [
        "one",
        "two"
      ],
      "title": "E",
      "type": "string"
    }
  },
  "properties": {
    "e": {
      "$ref": "#/definitions/E"
    }
  },
  "required": [
    "e"
  ],
  "title": "A",
  "type": "object"
}
```

2023-09-14 13:33 UTC, PrettyWood approved these changes

2023-09-28 17:11 UTC, PrettyWood requested changes

2023-09-28 17:11 UTC, PrettyWood commented on toucan_connectors/google_big_query/google_big_query_connector.py
>      data_source_model: GoogleBigQueryDataSource
a virer

2023-09-29 08:01 UTC, lukapeschke commented on toucan_connectors/google_big_query/google_big_query_connector.py
>      data_source_model: GoogleBigQueryDataSource
[a9c0377](https://github.com/ToucanToco/toucan-connectors/pull/1272/commits/a9c0377de178b90c524349ed0caf942a2243ecea)

2023-09-29 08:01 UTC, lukapeschke commented on pyproject.toml
> +pydantic = "^2.3.0"
[d0dc261](https://github.com/ToucanToco/toucan-connectors/pull/1272/commits/d0dc26143b9481c443f2c98a9d9c8fe4d767555e)

2023-09-29 08:01 UTC, lukapeschke commented on README.md
> +class MyTypeConnector(ToucanConnector,data_source_model=MyTypeDataSource):
[3b3eb12](https://github.com/ToucanToco/toucan-connectors/pull/1272/commits/3b3eb12d6e96e12c114ae8aca3a02afc236bf615)

2023-12-15 11:14 UTC, merged