fix(oracle_sql): pass parameters to pandas read_sql as numbered parameters
ToucanToco/toucan-connectors pull request #1666
Opened 2024-06-07 14:24 UTC by julien-pinchelimouroux

## Change Summary

 - OracleSQL: pass parameters as numbered to `read_sql`

2024-06-10 09:09 UTC, lukapeschke requested changes

2024-06-10 09:09 UTC, lukapeschke commented on toucan_connectors/oracle_sql/oracle_sql_connector.py
> +        )
Should you also specify `convert_to_printf=False` here ?

2024-06-10 09:09 UTC, lukapeschke commented on toucan_connectors/common.py
> +def convert_to_numbered_vars_paramstyle(query_string: str, params_values: dict) -> tuple[str, tuple[Any]]:
It's called the `numeric` param style: https://peps.python.org/pep-0249/#paramstyle

Also, could you please add parametrized unit tests for this function ? If the oracle connectors is discontinued at some point, we won't have any tests left

2024-06-10 12:19 UTC, fspot commented on toucan_connectors/common.py
> +    """Takes a query in pyformat paramstyle and transforms it in numbered paramstyle
```suggestion
    """Takes a query in pyformat paramstyle and transforms it in numeric paramstyle
```

2024-06-10 12:22 UTC, fspot approved these changes

2024-06-11 07:31 UTC, lukapeschke approved these changes

2024-06-11 15:09 UTC, merged