fix: merge api results after their transformations (TCTC-9634)
ToucanToco/toucan-connectors pull request #1807
Opened 2024-10-31 10:57 UTC by julien-pinchelimouroux

## Why

API results where appended before any user's configured transformations (filters, flatten). We have to append resulted dataframes.
Moreover, APIs can return directly json objects, which created invalid results merging.
In addition, we have to add a data_length_filter to offset_limit pagination in case of the data result isn't relevant to compute the data length.

2024-10-31 13:41 UTC, davinov approved these changes
Indeed, thanks for this fix and the associated test!

2024-11-04 14:05 UTC, lukapeschke requested changes
Thanks! few nits here and there. And `pandas.concat` should be compatible with v1 and v2, AND do what you want :slightly_smiling_face:

2024-11-04 14:05 UTC, lukapeschke commented on toucan_connectors/http_api/pagination_configs.py
> +            "It must point to a list of results. " + FilterSchemaDescription
```suggestion
            "Filter to access the received data. Allows to compare its length to the limit value. "
            "It must point to a list of results. " + FilterSchemaDescription
```

Wouldn't `data_filter` be a better name ?

2024-11-04 14:05 UTC, lukapeschke commented on CHANGELOG.md
> +- HTTP API: Add `data_length_filter` offset pagination config field to determine which part of data must be used to compute the data length.
Shouldn't this be in the `Added` section ?

2024-11-04 14:05 UTC, lukapeschke commented on CHANGELOG.md
> +- HTTP API: Extract API results dataframes separately and merge them after.
The changelog is destined to end-users. Instead of explaining the code change, could you explain the issue that was solved ?

2024-11-06 08:39 UTC, lukapeschke approved these changes
thx!

2024-11-06 08:42 UTC, merged