feat(oauth): Modified Google Sheets
ToucanToco/toucan-connectors pull request #190
Opened 2020-08-06 16:28 UTC by testinnplayin

Beginning of replacing Bearer API in Google Sheets

## Change Summary

- BREAKING CHANGES TO AIRCALL

- CONNECTOR_REGISTRY now returns a Google Sheets API with auth_flow
property

- No tests yet

## Related issue number

## Checklist

* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%
* [ ] Documentation reflects the changes where applicable

2020-08-06 16:29 UTC, testinnplayin commented
![](https://github.trello.services/images/mini-trello-icon.png) [(1) Remplacer strings liés à Bearer dans Google Sheets](https://trello.com/c/aWvk08LH/672-1-remplacer-strings-li%C3%A9s-%C3%A0-bearer-dans-google-sheets)

2020-08-10 08:53 UTC, testinnplayin commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) ETQC, lorsque je clique sur le bouton "google sheets", on ouvre une popup autoriser](https://trello.com/c/bjIZgLch/654-3-etqc-lorsque-je-clique-sur-le-bouton-google-sheets-on-ouvre-une-popup-autoriser)

2020-08-26 10:12 UTC, erenard requested changes
Je crois qu'il manque un type de connector dans le registry.

2020-08-26 10:12 UTC, erenard commented on toucan_connectors/__init__.py
>          connector_infos['connector'] = connector_cls
Ou alors le GoogleSheet doit avoir le connector GoogleSheets2

2020-08-26 10:15 UTC, testinnplayin commented on toucan_connectors/__init__.py
>          connector_infos['connector'] = connector_cls
yes t'a raison... oups, j'ai oublié de le remettre

2020-08-26 11:20 UTC, erenard approved these changes
Let's iterate from here !

2020-08-26 12:05 UTC, merged