feat(googlesheets2): first pass at passing token
ToucanToco/toucan-connectors pull request #198
Opened 2020-08-26 15:28 UTC by testinnplayin

## Change Summary

## Related issue number

## Checklist

* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%
* [ ] Documentation reflects the changes where applicable

2020-08-26 15:29 UTC, testinnplayin commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) ETQC, je peux passer ces tokens pour faire des requêtes au connecteur Google Sheets](https://trello.com/c/49q2y8NH/659-3-etqc-je-peux-passer-ces-tokens-pour-faire-des-requ%C3%AAtes-au-connecteur-google-sheets)

2020-08-26 15:37 UTC, testinnplayin commented
![](https://github.trello.services/images/mini-trello-icon.png) [(2) Au moment de passer la requête vers le connecteur, laputa cherche les secrets dans la BDD collection des secrets et les passe sous forme de dict au connecteur](https://trello.com/c/MSJoICEG/769-2-au-moment-de-passer-la-requ%C3%AAte-vers-le-connecteur-laputa-cherche-les-secrets-dans-la-bdd-collection-des-secrets-et-les-passe-s)

2020-08-26 15:39 UTC, testinnplayin commented
![](https://github.trello.services/images/mini-trello-icon.png) [(1) Le connecteur Google Sheets utilise le secret pour autoriser la connexion](https://trello.com/c/ZecnTfcP/770-1-le-connecteur-google-sheets-utilise-le-secret-pour-autoriser-la-connexion)

2020-08-31 08:01 UTC, testinnplayin commented on toucan_connectors/toucan_connector.py
> +    def _retrieve_data(self, data_source: ToucanDataSource, secrets: Optional[dict]):
Ok merci !

2020-08-31 15:54 UTC, testinnplayin commented on toucan_connectors/google_sheets_2/google_sheets_2_connector.py
> +        self, data_source: GoogleSheets2DataSource, secrets: Optional[dict] = None
```suggestion
        self, data_source: GoogleSheets2DataSource, secrets: dict
```

2020-08-31 15:54 UTC, testinnplayin commented on toucan_connectors/google_sheets_2/google_sheets_2_connector.py
> +        self, data_source: GoogleSheets2DataSource, secrets: Optional[dict] = None
Je pense que `secrets` ne devrait pas être optionnel... justement je pensais (dans une autre PR) faire une vérification sur `**kwargs` pour être sûr d'avoir `secrets` et un `access_token` dedans.

C'est vrai que ça peut être Google qui envoie l'erreur mais je trouve que c'est un peu dommage d'envoyer un fetch qui ne peut pas être valide depuis le départ.

Qu'en penses-tu ?

2020-08-31 15:54 UTC, testinnplayin commented on toucan_connectors/toucan_connector.py
> +            k: v for k, v in kwargs.items() if k in signature(self._retrieve_data).parameters
Je ne comprends pas... je pensais comprendre dans le sens que ça serait bien d'avoir un check sur les paramètres dans `_retrieve_data` mais dans cette méthode on a un `**kwargs` qui peut être n'importe quoi... :thinking:

2020-08-31 15:57 UTC, testinnplayin commented
J'aurais beaucoup aimé que tu n'effaces pas le code que j'avais créé.

2020-08-31 15:57 UTC, PrettyWood commented on toucan_connectors/google_sheets_2/google_sheets_2_connector.py
> +        self, data_source: GoogleSheets2DataSource, secrets: Optional[dict] = None
Peu importe optionnel ou pas ca je te laisse gerer. Je voulais juste mettre en evidence qu'il fallait à mes yeux ne pas forcer tous les connecteurs à supporter `secrets` d'où la modif cote `ToucanConnector`.
Apres le code de GoogleSheets je te laisse voir pour le coup c'est toi qui sait ce que tu veux faire

2020-08-31 15:58 UTC, PrettyWood commented
@testinnplayin Je n'ai rien effacé tu peux juste revert mon commit...je ne comprends pas le souci

2020-08-31 16:02 UTC, testinnplayin commented
C'est moi qui me suis trompée... je m'excuse !

2020-09-01 14:13 UTC, davinov requested changes

2020-09-01 14:13 UTC, davinov commented on toucan_connectors/google_sheets_2/google_sheets_2_connector.py
> +    def _set_secrets(self, secrets: Dict[str, str]):
This method should be public so we can call it

2020-09-01 14:15 UTC, davinov approved these changes
Thanks for the modifications
Having a set_secrets method is way better than passing it from one function to another ^^

2020-09-01 15:24 UTC, PrettyWood commented on tests/test_connector.py
> +def test_get_slice(mocker):
```suggestion
def test_get_slice():
```

2020-09-01 17:21 UTC, PrettyWood approved these changes

2020-09-02 07:02 UTC, merged