feat(gsheets2): added hidden properties
ToucanToco/toucan-connectors pull request #208
Opened 2020-09-16 13:10 UTC by testinnplayin

## Change Summary

We added a class to hide certain properties from the user. These can be divided into two main categories: flags and non-flags.

Flags are properties that are required by the front to do something. In this case `auth_flow_id` is for initiating the oauth dance.

Non-flags are everything else. Non-flags can be divided into two categories: static and dynamic. Static non-flags are kept on the connector itself and have a '_' at the front of their name. Dynamic ones are kept on the new class. The reason why we put the static non-flags is so that we don't have to return them if we don't want to when we fetch hidden properties from the class that contains them.

On the front-end, we will eventually want to hide all properties that are stored in 'hidden_properties' on the connector. Those properties that begin with a '_' are hidden automatically.

Dynamic properties cannot be hidden with a '_' in front of their variable name because we can't set them afterwards.

## Related issue number

[https://github.com/ToucanToco/toucan-connectors/issues/206](https://github.com/ToucanToco/toucan-connectors/issues/206)

## Checklist

* [X] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%
* [ ] Documentation reflects the changes where applicable

2020-09-16 14:24 UTC, testinnplayin commented
![](https://github.trello.services/images/mini-trello-icon.png) [(8) EPIC ETQC, je ne vois pas des propriétés privées dans le formulaire d'édition du connecteur GoogleSheets2](https://trello.com/c/woTQo3Fh/850-8-epic-etqc-je-ne-vois-pas-des-propri%C3%A9t%C3%A9s-priv%C3%A9es-dans-le-formulaire-d%C3%A9dition-du-connecteur-googlesheets2)

2020-09-17 07:59 UTC, davinov requested changes
Thanks for all this work and research you put it in.

However, reading the code, I feel weird  about the `hidden_properties` method.
First : it contains only a token for now, so maybe a generic name is not appropriate to make following readers understand what this is about. IMO this name would have make sense if this was in the base class `ToucanConnectors` when we have no clue what will be inside.
Second : I have suggestion to ease the API of the connector. Since what the connector needs is to retrieve an access_token using the auth_flow_id, maybe it's easier to just pass to a connector the method that does this, and then the connector will be able use it when needed. What do you think about this ?

2020-09-17 07:59 UTC, davinov commented on doc/connectors/google_sheets_2.md
> +The `hidden_properties` propertie contains the `access_token` and a `refresh_token` (if there is one) in a class called `GoogleSheets2HiddenProperties`. Though `hidden_properties` is optional during
```suggestion
The `hidden_properties` property contains the `access_token` and a `refresh_token` (if there is one) in a class called `GoogleSheets2HiddenProperties`. Though `hidden_properties` is optional during the initial creation of the connector, it is necessary for when the user wants to make requests using the connector. If there is no `access_token`, an Exception is thrown. This is a dynamic property (not a static one).
```

2020-09-17 07:59 UTC, davinov commented on doc/connectors/google_sheets_2.md
> +The `_baseroute` is fixed and is 'https://sheets.googleapis.com/v4/spreadsheets/'. It too is hidden from being rendered in the front. It is a static *non-flag*
```suggestion
The `_baseroute` is fixed and is 'https://sheets.googleapis.com/v4/spreadsheets/'. It too is hidden from being rendered in the front. It is a static property.
```
Or class property (something that doesn't change with the instance)

2020-09-17 07:59 UTC, davinov commented on doc/connectors/google_sheets_2.md
> +The `_auth_flow` property marks this as being a connector that uses the connector_oauth_manager for the oauth dance. It is hidden from being rendered in the front but appears in the front as a flag f
```suggestion
The `_auth_flow` property marks this as being a connector that uses the connector_oauth_manager for the oauth dance. It is hidden from being rendered in the front but appears in the front as a flag for initiating the oauth dance. It is a static *property*.
```
I prefer we use the term _property_, which has a clear meaning in Python.
Flag is less clear : it suggest a boolean, a feature-flag, and many other things.

2020-09-17 07:59 UTC, davinov commented on toucan_connectors/google_sheets_2/google_sheets_2_connector.py
> +    This class contains dynamic hidden properties for Google Sheets 2 that are not flags
```suggestion
    This class contains dynamic hidden properties for Google Sheets 2 that are not configured directly by a user, like tokens retrieved via OAuth2
```

2020-09-17 07:59 UTC, davinov commented on toucan_connectors/google_sheets_2/google_sheets_2_connector.py
> +    # flagging variable; required for initiating the oauth dance
:+1:

2020-09-17 07:59 UTC, davinov commented on toucan_connectors/google_sheets_2/google_sheets_2_connector.py
> +    _baseroute = 'https://sheets.googleapis.com/v4/spreadsheets/'
Could we make that a real class property by the way ? That will save some db space and prevent to send it to the front-end

2020-09-17 07:59 UTC, davinov commented on toucan_connectors/google_sheets_2/google_sheets_2_connector.py
> +class GoogleSheets2HiddenProperties(BaseModel):
I don't really see the value of using a Pydantic BaseModel here. Their usage is to validate/enforce a model, when some data comes from an uncertain source, like a form filled by someone, or an unknown database without a schema.
I wonder if a very simple dataclass would be enough here.

2020-09-17 07:59 UTC, davinov commented on toucan_connectors/google_sheets_2/google_sheets_2_connector.py
> +    _auth_flow = 'oauth2'
I took a few minutes to look at Pydantic's docs and saw the keep_untouched config option.
https://pydantic-docs.helpmanual.io/usage/model_config/

Is that worth to try ?

2020-09-17 08:24 UTC, testinnplayin commented
I put in generic terms because I'm thinking of the future of the connectors. We could do similar things with other connectors if we wanted to use this route.

If we have a retry policy in place for the connector, we might need the refresh token in secrets as well and not just the access token.

I'm not sure about your second point sorry.

2020-09-17 09:27 UTC, closed without merging