feat(postgresconnector): introspection in data source form
ToucanToco/toucan-connectors pull request #307
Opened 2021-01-22 17:26 UTC by raphaelvignes

## Change Summary

I added
## Related issue number

## Checklist

* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%
* [ ] Documentation reflects the changes where applicable

2021-01-27 13:43 UTC, hachichaud commented on tests/docker-compose.yml
> +    - POSTGRES_DB=ubuntu
Pourquoi le changement ?

2021-01-27 13:44 UTC, hachichaud commented on toucan_connectors/postgres/postgresql_connector.py
> +        'your_table")',
```suggestion
        'your_table limit 50")',
```

2021-01-27 13:54 UTC, hachichaud requested changes
Juste la description du champ table, sinon lgtm :)

2021-01-27 14:25 UTC, raphaelvignes commented on toucan_connectors/postgres/postgresql_connector.py
> +        'your_table")',
Je vais virer le limit 50 de la docstring comme sur les autres.

2021-01-28 09:44 UTC, hachichaud commented on tests/docker-compose.yml
> +    - POSTGRES_DB=ubuntu
ok merci pour l'explication 👍

2021-01-28 09:47 UTC, hachichaud commented on toucan_connectors/postgres/postgresql_connector.py
> +            dbname=database if database else 'postgres',
est-ce que ce fallback par défaut n'est pas déjà fait plus haut ⬆️  ?

```
def get_connection_params(self, *, database='postgres'):
```

2021-01-28 09:50 UTC, raphaelvignes commented on toucan_connectors/postgres/postgresql_connector.py
> +            dbname=database if database else 'postgres',
Bonne remarque, il est fait si le paramètre n'est pas passé mais dans get_form,
je passe ceci: 
`        connection = pgsql.connect(
            **connector.get_connection_params(database=current_config.get('database'))
        )
        `
    Je vais modifier avec ceci: 
    `        connection = pgsql.connect(
            **connector.get_connection_params(database=current_config.get('database', 'postgres'))
        )`

2021-01-28 10:45 UTC, hachichaud approved these changes
👍

2021-01-28 18:02 UTC, merged