feat(Oracle): Introspection in Oracle Data Source
ToucanToco/toucan-connectors pull request #309
Opened 2021-01-25 22:44 UTC by raphaelvignes

Added introspection in Oracle Data source (only for Tables as Database is set in Connector's form)
## Checklist

* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%

2021-01-27 13:27 UTC, hachichaud commented on toucan_connectors/oracle_sql/oracle_sql_connector.py
> +        'your_table")',
```suggestion
        'get (equivalent to "SELECT * FROM '
        'your_table limit 50")',
```

2021-01-27 13:37 UTC, hachichaud commented on toucan_connectors/oracle_sql/oracle_sql_connector.py
> +            cursor.execute("""select table_name from USER_TABLES""")
est-ce qu'ici on ne veut afficher que les tables qui sont owned par l'utilisateur, ou toutes les tables accessibles (en faisant `from all_tables` ) ? cf https://www.oracletutorial.com/oracle-administration/oracle-show-tables/ 
Je ne sais pas si dans nos cas d'usages, les deux sont équivalents. On pourrait avoir des tables qui accessibles en lecture par ex, mais que notre utilisateur ne possèderait pas

2021-01-27 13:39 UTC, raphaelvignes commented on toucan_connectors/oracle_sql/oracle_sql_connector.py
> +        'your_table")',
Je vais faire la même chose que dans le connecteur mssql -> si on définit une table et pas de query ce sera un select * from table. Comme ça les concepteurs pourront récupérer directement toute la table.

2021-01-27 13:40 UTC, hachichaud requested changes
Juste un changement pour que la docstring du champs table match la requête qui est faite, et une question sur le "show tables" qui est fait

2021-01-27 13:41 UTC, raphaelvignes commented on toucan_connectors/oracle_sql/oracle_sql_connector.py
> +            cursor.execute("""select table_name from USER_TABLES""")
Bonne idée. 
C'est plus pertinent avec all_tables.

2021-01-27 14:34 UTC, raphaelvignes commented
Merci pour la revue !

2021-01-27 14:53 UTC, hachichaud commented on toucan_connectors/oracle_sql/oracle_sql_connector.py
> +            # Filter tables starting with an '_' because strlist_to_enum cannot
Je suis étonnée par cette histoire de `_`
Où est-ce que ca bloque ?

2021-01-27 15:01 UTC, raphaelvignes commented on toucan_connectors/oracle_sql/oracle_sql_connector.py
> +            # Filter tables starting with an '_' because strlist_to_enum cannot
Ici: 
![image](https://user-images.githubusercontent.com/71276735/106009650-dc3a7680-60b8-11eb-97b4-7b95f6d0a293.png)

2021-01-28 09:50 UTC, hachichaud approved these changes
LGTM!

2021-01-28 10:33 UTC, raphaelvignes commented
Merci pour la revue !

2021-01-28 10:33 UTC, merged