Snowflake: Add OAuth connection support
ToucanToco/toucan-connectors pull request #311
Opened 2021-01-27 15:44 UTC by kadjou1

## Change Summary

This PR adds a way to handle a connection through OAuth for Snowflake.
The Snowflake model was changed to handle multiple ways of authentication (plain text and oauth for now), the OAuth authentication is already handled by the Snowflake python client, this PR only adds a way for the user to supply a OAuth token at the creation of the connector

## Related issue number

None

## Checklist

* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%
* [ ] Documentation reflects the changes where applicable

2021-01-27 16:06 UTC, raphaelvignes reviewed
Merci pour cette évolution du connecteur Snowflake ! 
J'ai une remarque un peu structurante, on peut en rediscuter.

2021-01-27 16:06 UTC, raphaelvignes commented on toucan_connectors/snowflake/snowflake_connector.py
> +                token=Template(self.authentication.oauth_token).render(),
Remarque pour la suite: avec cette logique on va pouvoir rentrer le token dans la config du connecteur et stocker le token dans l'etl_config et l'interpoler ici via un Template jinja. 

Par contre: 
1) Comment est-ce qu'on récupère ce token ? Je n'ai plus la discussion en tête mais il me semblait que dans le mode 'oauth', le connecteur devait implémenter la logique oauth en lui passant les client_id et client_secret . 
2) Si le token expire, comment va t'on le rafraîchir ? J'ai l'impression qu'avec cette logique, il faut recréer le connecteur à chaque fois.

2021-01-27 16:06 UTC, raphaelvignes commented on toucan_connectors/snowflake/snowflake_connector.py
> +class SnowflakeAuthentication(BaseModel):
Bonne idée cette nouvelle classe :+1:

2021-01-27 16:20 UTC, hachichaud requested changes
Je pense que tu as voulu aller un peu loin avec le formulaire :) 
La logique de connexion est là, mais je préfère qu'on garde une structure du modèle de connecteur plate comme sur tous les autres.
Pour moi ici tu cherches à régler l'affichage du formulaire avec le modèle, du coup ca mélange un peu deux aspects. 
On pourra regarder plus tard pour bien grouper les options et ajouter des logiques plus complexes.

Pour résumer : 
- ajout d'une methode get_connection_params
- casse du  `Authentication_Mechanism` , il me semble qu'on utilise plutot Pascal.
- modèle à simplifier (retirer le niveau supplémentaire pour l'authentification)

2021-01-27 16:20 UTC, hachichaud commented on toucan_connectors/snowflake/snowflake_connector.py
> +class SnowflakeAuthentication(BaseModel):
Finalement, vu que le formulaire devra être amélioré par la suite et qu'on n'a pas la logique de cacher le champs password ou token. Je trouve que c'est dommage d'autant modifier le modèle du connecteur ici, en passant par un sous modèle pour l'authentification.
On a un système pour grouper des champs coté front et améliorer l'affichage du formulaire. 
Ici je préfère garder la structure simple qu'on avait avant

2021-01-27 16:20 UTC, hachichaud commented on toucan_connectors/snowflake/snowflake_connector.py
> +                user=self.authentication.user,
Ici tu pourrais implémenter la méthode `get_connection_params` comme par exemple sur https://github.com/ToucanToco/toucan-connectors/blob/master/toucan_connectors/mysql/mysql_connector.py#L116

2021-01-27 16:21 UTC, hachichaud commented on toucan_connectors/snowflake/snowflake_connector.py
> +class SnowflakeAuthentication(BaseModel):
haha on n'est pas d'accord 😬 
(je suis ouverte à la discussion ! )

2021-01-27 16:50 UTC, raphaelvignes commented on toucan_connectors/snowflake/snowflake_connector.py
> +class SnowflakeAuthentication(BaseModel):
En fait ça rend le code plus lisible je dirais mais ça peut potentiellement impacter l’expérience utilisateur. Donc pas nécessaire.

2021-01-28 09:32 UTC, kadjou1 commented on toucan_connectors/snowflake/snowflake_connector.py
> +class SnowflakeAuthentication(BaseModel):
J'ai remis à plat le modèle du coup.

2021-01-28 09:32 UTC, kadjou1 commented on toucan_connectors/snowflake/snowflake_connector.py
> +class Authentication_Mechanism(str, Enum):
Changé !

2021-01-28 09:33 UTC, kadjou1 commented on toucan_connectors/snowflake/snowflake_connector.py
> +                user=self.authentication.user,
Fait !

2021-01-28 09:43 UTC, hachichaud approved these changes
Merci pour les changements 🙏 Ca m'a l'air bon :)
Je veux bien un petit guru pour tester ensuite

2021-01-28 10:48 UTC, hachichaud commented on toucan_connectors/snowflake/snowflake_connector.py
> +                token=Template(self.authentication.oauth_token).render(),
Réponse pour la postérité. Résumé de notre discussion de ce matin :)
1. On fait comme pour l'usage du http api sur certains clients (avec templating de valeurs récupérées via l'authentifiaction) - donc pas d'échange oauth à traiter ici - dans notre cas ce sera traité coté idp
2. en effet pas de mécanisme de refresh. C'est aussi un pb qu'on a avec l'usage du http api. C'est à faire

2021-01-29 12:54 UTC, kadjou1 commented
@raphaelvignes j'ai ajouté un commit de bump de version pour pouvoir release cette nouvel version du connecteur Snowflake, est-ce que tu y vois un inconvénient ?

2021-01-29 13:15 UTC, raphaelvignes commented
Aucun, mais Il faut que tu passes en 0.45.5 car j'ai sorti une 0.45.4 pour l'introspection SQL

2021-02-01 12:51 UTC, merged