feat(Github Connector): enable incremental capability
ToucanToco/toucan-connectors pull request #312
Opened 2021-01-27 18:07 UTC by raphaelvignes

## Change Summary

For the Github's Business in a Box, we need to be able to stop traversing pagination when the connector detects a pull request we retrieved previously. 
This logic won't be used in current Business in a Box but in the next Architecture with the scheduled extraction script.

The idea will be: in the scheduled Github extraction script, we will retrieve the latest extracted PR from the client's bucket and give it to an instanciated Github Connector, this way it will only extract the required pages & PR.

## Checklist

* [x] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%

2021-01-28 13:31 UTC, hachichaud requested changes
Je t'ai mis qques petits commentaires. J'ai principalement buggé sur le nom `latest_retrieved_object ` qui est le meme partout mais qui ne représente pas tjs la même chose.
Sinon ca a l'air de faire le taf 👍 , même si je ne connais pas bien l'usage coté laputa
Je laisse à Fred le soin de valider plus en détail :p

2021-01-28 13:31 UTC, hachichaud commented on toucan_connectors/github/github_connector.py
> +            if latest_retrieved_object and dataset == 'pull requests':
```suggestion
            if latest_retrieved_object and dataset == GithubDataset.pull_requests:
```
peut-être ?

2021-01-28 13:31 UTC, hachichaud commented on toucan_connectors/github/github_connector.py
> +                    if dataset == 'pull requests':
Tu es déjà dans le cas dataset == PR

2021-01-28 13:31 UTC, hachichaud commented on toucan_connectors/github/github_connector.py
> +                        : [pr['PR Name'] for pr in formatted_data].index(latest_retrieved_object)
Je ne sais pas si tu as beaucoup de formatted_data. Mais peut etre que tu peux récupérer l'index du latest_retrieved_object directement. Si >= 0 tu l'utilises pour slicer ta liste.
T'économises une recherche 🤷‍♀️

2021-01-28 19:19 UTC, raphaelvignes commented on toucan_connectors/github/github_connector.py
> +            if latest_retrieved_object and dataset == 'pull requests':
Oui merci :+1:

2021-01-28 19:29 UTC, raphaelvignes commented on toucan_connectors/github/github_connector.py
> +        latest_retrieved_object=None,
oui ça vaut le coup, je reconnais que ce n'est pas super clair ! 
latest_retrieved_object est soit le nom d'une PR soit le nom d'un user. 
ça va permettre d'arrêter l'extraction via get_pages une fois que l'on a extrait les nouvelles données depuis latest_retrieved_object.

2021-01-28 19:30 UTC, raphaelvignes commented on toucan_connectors/github/github_connector.py
> +                    if dataset == 'pull requests':
Oui, bien vu.

2021-01-28 20:33 UTC, raphaelvignes commented on toucan_connectors/github/github_connector.py
> +                        : [pr['PR Name'] for pr in formatted_data].index(latest_retrieved_object)
Bonne remarque ! Cette économie sera précieuse quand on commencera à scaler et que l'on aura beaucoup de client avec une extraction simultanée.

2021-01-28 20:34 UTC, raphaelvignes commented
Merci pour la revue !

2021-01-29 08:27 UTC, hachichaud commented on toucan_connectors/github/github_connector.py
> +        :param: latest_retrieved_object str of either the latest user name or pull request name retrieved
tu as 2 docs string pour le meme parametre ici ^^

2021-01-29 08:31 UTC, raphaelvignes commented on toucan_connectors/github/github_connector.py
> +        :param: latest_retrieved_object str of either the latest user name or pull request name retrieved
La fatigue sans doute ...

2021-01-29 08:49 UTC, hachichaud approved these changes
LGTM 👍

2021-02-01 08:03 UTC, merged

2021-02-15 15:18 UTC, raphaelvignes commented
![](https://github.trello.services/images/mini-trello-icon.png) [(5) Extraire la donnée avec une date de début et jusqu'à atteindre l'historique [3]](https://trello.com/c/U4mHMB3g/245-5-extraire-la-donn%C3%A9e-avec-une-date-de-d%C3%A9but-et-jusqu%C3%A0-atteindre-lhistorique-3)