fix(snowflake): Apply query parameters through snowflake's client
ToucanToco/toucan-connectors pull request #321
Opened 2021-02-09 11:27 UTC by kadjou1

## Change Summary

This PR discards the usage of `nosql_apply_parameters_to_query` in the snowflake connector in order to use snowflake's own way of applying parameters to a query.

This PR also pins the version of `pyarrow` since the snowflake python client is not compatible (for now) with any version of pyarrow >= 0.18.

## Related issue number

None

## Checklist

* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%
* [ ] Documentation reflects the changes where applicable

2021-02-10 13:29 UTC, hachichaud requested changes
C'est bien de découper ton code pour alléger la fonction principale. 
Du coup tu dois en profiter pour tester la logique.
Typiquement pour moi lorsqu'on commence à mettre des conditions, c'est souvent un signe que tester est pertinent.
Là il y a quand même une vérification sur le contenu d'une string, qui entraine un appel de fonction différent selon le résultat => à tester :) 
Tu peux aussi vérifier que ca marche avec select et SELECT

2021-02-10 13:29 UTC, hachichaud commented on toucan_connectors/snowflake/snowflake_connector.py
> +            return pd.DataFrame.from_dict(query_res.fetchall())
Je suis pas forcément d'accord avec le fait de ne pas tester ce bout de code. 
Justement, on a 2 cas différents, ca me parait pertinent de tester.
Si par ex tu te retrouves dans le futur à ajouter un autre type de query à exécuter, le test te permettra de voir que tu n'introduis pas de régression.

2021-02-10 13:29 UTC, hachichaud commented on toucan_connectors/snowflake/snowflake_connector.py
> +        cursor.execute(f'USE WAREHOUSE {warehouse}')
est-ce que cette ligne est nécessiaire d'ailleurs ? vu qu'on se connecte en précisant une warehouse plus haut

2021-02-10 13:29 UTC, hachichaud commented on toucan_connectors/snowflake/snowflake_connector.py
> +        # See `_execute_query` for more detail
Je ne pense pas que ce commentaire apporte quelque chose par rapport à la ligne du dessous
```suggestion
```

2021-02-10 13:29 UTC, hachichaud commented on toucan_connectors/snowflake/snowflake_connector.py
> +        data retrieval in `_retrieve_data`.
```suggestion
        results. 
```
Ca ne me parait pas nécessaire de mettre ce commentaire. En général c'est pour ca qu'on découpe en fonction.
A la limite tu peux expliquer pourquoi il y a plusieurs manières de récupérer les données.

2021-02-11 08:24 UTC, kadjou1 commented on toucan_connectors/snowflake/snowflake_connector.py
> +            return pd.DataFrame.from_dict(query_res.fetchall())
Fixé !

2021-02-11 08:24 UTC, kadjou1 commented on toucan_connectors/snowflake/snowflake_connector.py
> +        # See `_execute_query` for more detail
Fixé !

2021-02-11 08:24 UTC, kadjou1 commented on toucan_connectors/snowflake/snowflake_connector.py
> +        data retrieval in `_retrieve_data`.
Fixé aussi !

2021-02-11 08:29 UTC, hachichaud approved these changes
👍 merci pour les tests :)

2021-02-11 08:42 UTC, kadjou1 commented on toucan_connectors/snowflake/snowflake_connector.py
> +        cursor.execute(f'USE WAREHOUSE {warehouse}')
A priori non, j'ai testé en local, les requêtes passent toujours du coup a priori on est bons sur le fait de supprimer ce statement :)

2021-02-11 10:14 UTC, hachichaud requested changes
Il faut adapter les tests au use warehouse (btw tu as pu faire un  vrai test pour etre sur que ca fonctionne sans ? je sais pas trop pourquoi c'etait là 🤔  )

2021-02-11 10:14 UTC, hachichaud commented on tests/snowflake/test_snowflake.py
> +        call('USE WAREHOUSE test_warehouse'),
du coup je pense que ce test n'est plus valable

2021-02-11 15:52 UTC, kadjou1 commented on tests/snowflake/test_snowflake.py
> +        call('USE WAREHOUSE test_warehouse'),
En effet, et pour le test en conditions réelles (donc requête envoyée depuis laputa), aucun souci ne s'est présenté suite à la suppression de ce statement.

2021-02-11 17:10 UTC, hachichaud approved these changes
lgtm :)

2021-02-12 13:43 UTC, merged