feat: linkedinads connector
ToucanToco/toucan-connectors pull request #334
Opened 2021-03-01 21:18 UTC by raphaelvignes

## Change Summary

Added linkedinads connector

## Checklist

* [x] Unit tests for the changes exist
* [] Tests pass on CI and coverage remains at 100%
* [ ] Documentation reflects the changes where applicable

2021-03-08 10:26 UTC, hachichaud commented on tests/linkedinads/test_linkedinads.py
> +def con(secrets_keeper):
Je préfèrerais un nom plus explicite. Là on pourrait parler de connection ou de connector, c'est difficile à savoir

2021-03-08 10:27 UTC, hachichaud commented on tests/linkedinads/test_linkedinads.py
> +def ds():
pareil un nom qui explique un peu plus explicitement ce qu'accomplit la method , ce n'est pas de refus

2021-03-08 10:30 UTC, hachichaud commented on toucan_connectors/linkedinads/doc.md
> +[documentation](https://docs.toucantoco.com/concepteur/power-apps-with-data/02-connectors.html#linkedinads-connector)
je suis allé voir la doc. On est ok avec le fait de mettre notre client ID en screenshot ?
meme si c'est un paramètre +/- public 🤔 
Ne serait-ce que pour éviter que les gens copient betement

2021-03-08 10:39 UTC, raphaelvignes commented on tests/linkedinads/test_linkedinads.py
> +def con(secrets_keeper):
:+1:

2021-03-08 10:40 UTC, raphaelvignes commented on tests/linkedinads/test_linkedinads.py
> +def ds():
Merci, pris en compte.

2021-03-08 10:41 UTC, raphaelvignes commented on toucan_connectors/linkedinads/doc.md
> +[documentation](https://docs.toucantoco.com/concepteur/power-apps-with-data/02-connectors.html#linkedinads-connector)
Bien vu, je mets ça à jour.

2021-03-08 10:43 UTC, hachichaud commented on toucan_connectors/linkedinads/linkedinads_connector.py
> +    auth_flow_id: Optional[str]
tu pourrais ajouter qque part commetn récupérer cet "auth flow id" ? je ne le vois pas dans la doc

2021-03-08 10:44 UTC, hachichaud commented on toucan_connectors/linkedinads/linkedinads_connector.py
> +    start_date: str = Field(..., title='Start date', description='Start date of the dataset')
ca vaut le coup d'ajouter le format de date attendu non ?
Vu que la date est parsed/split plus bas

2021-03-08 10:45 UTC, hachichaud commented on toucan_connectors/linkedinads/linkedinads_connector.py
> +        )
cf commentaire sur le champs plus haut.
Mettre au moins en tooltip le format de date attendu. Sinon peut etre ici tenter une lecture de la date en devinant le type, lorsque le split échoue ?

2021-03-08 10:47 UTC, hachichaud commented on toucan_connectors/linkedinads/linkedinads_connector.py
> +        )
un usage de https://docs.python.org/3/library/datetime.html peut etre ?

2021-03-08 10:47 UTC, hachichaud commented on toucan_connectors/linkedinads/linkedinads_connector.py
> +            splitted_end = data_source.end_date.split('/')
meme remarque que plus haut. Au moins factoriser cette logique

2021-03-08 10:54 UTC, hachichaud commented on toucan_connectors/linkedinads/linkedinads_connector.py
> +        Test the Google Sheets connexion.
```suggestion
        Test the Linkedin adds ? connexion.
```

2021-03-08 10:54 UTC, hachichaud commented on toucan_connectors/linkedinads/linkedinads_connector.py
> +        Test the Google Sheets connexion.
un reste de copié collé ?

2021-03-08 10:57 UTC, hachichaud requested changes
des petits commentaires par ci par là, mais sinon top ! 
Tres bonne idée d'avoir ajouté le json to table

2021-03-08 11:03 UTC, raphaelvignes commented
Merci pour la revue

2021-03-08 11:08 UTC, raphaelvignes commented on toucan_connectors/linkedinads/doc.md
> +[documentation](https://docs.toucantoco.com/concepteur/power-apps-with-data/02-connectors.html#linkedinads-connector)
Changé.

2021-03-08 11:10 UTC, raphaelvignes commented on toucan_connectors/linkedinads/linkedinads_connector.py
> +    auth_flow_id: Optional[str]
En fait, il est créé automatiquement pendant le processus d'authentification oauth. 
Je rajoute un commentaire.

2021-03-08 11:11 UTC, raphaelvignes commented on toucan_connectors/linkedinads/linkedinads_connector.py
> +    start_date: str = Field(..., title='Start date', description='Start date of the dataset')
oui

2021-03-08 11:14 UTC, raphaelvignes commented on toucan_connectors/linkedinads/linkedinads_connector.py
> +        Test the Google Sheets connexion.
:facepalm:

2021-03-08 11:29 UTC, raphaelvignes commented on toucan_connectors/linkedinads/linkedinads_connector.py
> +            splitted_end = data_source.end_date.split('/')
j'ai utilisé `dateutil.parser` pour gérer les cas où le format de date entré n'est pas le bon.

2021-03-09 14:06 UTC, hachichaud commented on toucan_connectors/linkedinads/linkedinads_connector.py
> +        splitted_start = dateutil.parser.parse(data_source.start_date)
attention avec le format ''dd/mm/yyy" parce qu'il est dépendant de la locale définie. Du coup si tu testes :
`parser.parse("01/02/1989")` tu peux obtenir le 2 janvier ou le 1 février.
Vu qu'ici on connait le format, on peut utiliser datetime.strptime (et pourquoi pas fallback sur parser.parse au cas où on catch une erreur)

2021-03-09 15:25 UTC, raphaelvignes commented on toucan_connectors/linkedinads/linkedinads_connector.py
> +        splitted_start = dateutil.parser.parse(data_source.start_date)
Merci, c'est fait.

2021-03-10 07:58 UTC, merged