fix(hubspot): improve documentation for Hubspot connector
ToucanToco/toucan-connectors pull request #337
Opened 2021-03-04 14:44 UTC by kadjou1

## Change Summary

This PR aims to clarify the current documentation for the Hubspot connector

## Checklist

* ~~[ ] Unit tests for the changes exist~~
* ~~[ ] Tests pass on CI and coverage remains at 100%~~
* [X] Documentation reflects the changes where applicable

2021-03-04 14:45 UTC, kadjou1 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(5) Hubspot Marketing - POC Connecteur](https://trello.com/c/Vgml1q1c/262-5-hubspot-marketing-poc-connecteur)

2021-03-04 15:25 UTC, hachichaud requested changes
Merci pour l'update de la doc et de la loop :)
J'ai repéré une typo, et j'ai une nouvelle question sur le format des données

2021-03-04 15:25 UTC, hachichaud commented on doc/connectors/hubspot.md
> +  name:    'Hubspot connector'
```suggestion
  name:    'Hubspot Connector'
```

Il me semble que c'est sensible à la casse

2021-03-04 15:25 UTC, hachichaud commented on doc/connectors/hubspot.md
> +    * `contact`
question : si le seul cas d'uage de "object_type" c'est le cas web-analytics et que dans ce cas là on ne peut mettre que `contact`, est-ce qu'on a besoin de faire remplir ce champs par l'utilisateur ?

2021-03-04 15:25 UTC, hachichaud commented on toucan_connectors/hubspot/hubspot_connector.py
> +            # }
du coup si je lis bien les datas renvoyées. 
Le dataframe qu'on va récupérer sera de la forme : 


0 | {company: 'Biglytics', createddate': '2019-121-12'} 
1 | {company: 'boop', createddate': '2019-12-12'} 

Il ne faudrait pas plutot faire :

```
data.append(r['properties'])

# puis 
pd.DataFrame(data)
```


pour obtenir : 

(index) | company | createddate
------ | ------|----------
0      | Biglytics   | '2019-121-12'
  1     | boop   | '2019-121-12'

2021-03-05 17:39 UTC, kadjou1 commented on doc/connectors/hubspot.md
> +  name:    'Hubspot connector'
C'est fixé !

2021-03-05 17:40 UTC, kadjou1 commented on doc/connectors/hubspot.md
> +    * `contact`
Dans l'idée oui car il n'y a pas que les contacts comme `object_type`, il faut les rajouter les valeurs suivantes dans le code du coup (yakfautqu'on en gros)

2021-03-05 17:40 UTC, kadjou1 commented on toucan_connectors/hubspot/hubspot_connector.py
> +            # }
J'ai éludé une partie des données pour le coup:
```
{
  "results": [
    {
      "properties": {
        "city": "Cambridge",
        "createdate": "2019-10-30T03:30:17.883Z",
        "domain": "biglytics.net",
        "hs_lastmodifieddate": "2019-12-07T16:50:06.678Z",
        "industry": "Technology",
        "name": "Biglytics",
        "phone": "(877) 929-0687",
        "state": "Massachusetts"
      }
    }
  ],
  "paging": {
    "next": {
      "link": "?after=NTI1Cg%3D%3D",
      "after": "NTI1Cg%3D%3D"
    }
  }
}
```

Mais pour le coup, c'est une partie qui va changer dans une PR qui doit arriver plus tard (le code est déjà sur [cette branche](https://github.com/ToucanToco/toucan-connectors/tree/f/hubspot_datasets_improvement))

2021-03-08 10:18 UTC, hachichaud commented on doc/connectors/hubspot.md
> +    * `contact`
dsl j'ai pas bien compris ta réponse 😅 
je crois quil y a des mots en trop

2021-03-08 10:52 UTC, hachichaud commented on doc/connectors/hubspot.md
> +    * `contact`
-> reponse :  plus tard on voudra pouvoir gérer plus d'object_type que ce quon sait faire pour l'instant. donc on laisse le champ

2021-03-08 10:52 UTC, hachichaud approved these changes
lgtm 👍

2021-03-08 11:04 UTC, merged