feat(hubspot): Improve Hubspot datasets management
ToucanToco/toucan-connectors pull request #340
Opened 2021-03-08 11:13 UTC by kadjou1

## Change Summary

This PR adds a better management of the data sent by hubspot when data is retireved through the connector.
By better management, it means that some data were deeply nested into the resulting data after a query was submitted to the Hubspot API and those data will be extracted to be visible in the resulting pandas dataframe

## Checklist

* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%
* [ ] Documentation reflects the changes where applicable

2021-03-08 11:16 UTC, kadjou1 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(5) Hubspot Marketing - récupération de datasets "business"](https://trello.com/c/Ob25gJLy/352-5-hubspot-marketing-r%C3%A9cup%C3%A9ration-de-datasets-business)

2021-03-08 15:39 UTC, raphaelvignes requested changes
Bravo pour cette PR :fire: ! 
Le catalogue de connecteur commence à lourdement s'agrandir ! 
J'ai mis quelques commentaires et une modif qui me semble importante.

2021-03-08 15:39 UTC, raphaelvignes commented on toucan_connectors/hubspot/helpers.py
> +def format_unified(data: List[dict]) -> pd.DataFrame:
Je trouve le nom de la fonction pas assez explicite. 
Si je ne me trompe pas, la dernière version de l'API est la V3, du coup format_V3_data ? Où quelque chose du genre ?

2021-03-08 15:39 UTC, raphaelvignes commented on toucan_connectors/hubspot/helpers.py
> +def format_webanalytics(data: List[dict]) -> pd.DataFrame:
Comme c'est très bien fait en dessous, je pense que tu peux ajouter un petit commentaire pour préciser que les données de cet endpoint ne se trouvent pas uniquement dans la clé properties.

2021-03-08 15:39 UTC, raphaelvignes commented on toucan_connectors/hubspot/helpers.py
> +def format_hubspot_response(dataset: str, data: List[dict]) -> pd.DataFrame:
Dans la même veine que les commentaires précédents, ici tu pourrais indiquer que la réponse de certains endpoints nécessitent un formatage spécifique et que cette fonction se charge de faire le mapping Réponse <-> Fonction de formatage

2021-03-08 15:39 UTC, raphaelvignes commented on toucan_connectors/hubspot/hubspot_connector.py
>      def _retrieve_data(self, data_source: HubspotDataSource) -> pd.DataFrame:
Je ne sais pas si c'est le meilleur endroit ici, mais il faudrait préciser que ce connecteur extrait des données de la version courante (V3?) et legacy de l'API qui ont des formats de réponses et paginations différents, d'où la distinction.

2021-03-08 15:39 UTC, raphaelvignes commented on toucan_connectors/hubspot/hubspot_connector.py
> +            return format_hubspot_response(data_source.dataset, data)
:+1:

2021-03-08 15:39 UTC, raphaelvignes commented on toucan_connectors/hubspot/hubspot_connector.py
>      query: str
Est-ce qu'ici c'est un champs query de type string dont on a besoin ? 
il me semble que l'on a plutôt besoin de passer des paramètres via un dictionnaire. (Il faudrait d'ailleurs tester ce cas). 
```
    parameters: dict = Field(
        None,
        description='METTRE LE LIEN VERS L'ACCUEIL DE LA DOC API HUBSPOT ICI',
    )
    ```

2021-03-09 09:32 UTC, kadjou1 commented on toucan_connectors/hubspot/helpers.py
> +def format_unified(data: List[dict]) -> pd.DataFrame:
Yes bonne remarque, c'est fixé :)

2021-03-09 09:32 UTC, kadjou1 commented on toucan_connectors/hubspot/helpers.py
> +def format_webanalytics(data: List[dict]) -> pd.DataFrame:
Yep, fixé !

2021-03-10 10:11 UTC, kadjou1 commented on toucan_connectors/hubspot/hubspot_connector.py
>      query: str
En effet, le champ query doit partir.

Par contre est-ce que rajouter un champ `parameters` ça ne serait pas mettre un peu la charrue avant les boeufs ici ?
Pour le moment il me semble qu'on a pas identifié de usecases à ce sujet.

2021-03-10 10:12 UTC, kadjou1 commented on toucan_connectors/hubspot/helpers.py
> +def format_hubspot_response(dataset: str, data: List[dict]) -> pd.DataFrame:
Fait ici : https://github.com/ToucanToco/toucan-connectors/pull/340/files#diff-b0bbc03df068e102cbea31a2104a9b3044f4911ca41eb9fbd75a0ddd675b58faR75-R79

2021-03-10 12:29 UTC, hachichaud commented on toucan_connectors/hubspot/helpers.py
> +def hubspot_api_format_v3(data: List[dict]) -> pd.DataFrame:
```suggestion
def format_hubspot_api_v3(data: List[dict]) -> pd.DataFrame:
```
 ? pour reprendre le meme genre de nommage que les autres fonctions de formattage

2021-03-10 12:36 UTC, hachichaud commented on toucan_connectors/hubspot/helpers.py
> +    stored under the properties, these formatting fuctions will extract these data
```suggestion
    stored under the properties, these formatting functions will extract these data
```

2021-03-10 12:39 UTC, hachichaud commented on toucan_connectors/hubspot/helpers.py
> +    # Extract the useful data instead of returning everything contained in the event
Pourquoi on ne prend pas tout ? Ca fait vraiment beaucoup ?
Je me dis que si des personnes utilisent hubspot avec des events custom elles pourraient vouloir retrouver les données ?
Si ca n'a pas de sens/d'utilité tu peux ignorer mon commentaire

2021-03-10 12:42 UTC, hachichaud commented on toucan_connectors/hubspot/helpers.py
> +    For more information, look at the dedicated documentation: https://developers.hubspot.com/docs/api/events/web-analytics
Pourquoi la route webanalytics est classée en legacy alors que la doc indique que l'API est en beta ?

2021-03-10 12:47 UTC, hachichaud commented on toucan_connectors/hubspot/helpers.py
> +    return pd.DataFrame(data)['properties']
ici on ne retourne pas un DataFrame mais une Serie pandas non ?

2021-03-10 12:48 UTC, hachichaud commented on toucan_connectors/hubspot/hubspot_connector.py
> +            return format_hubspot_response(data_source.dataset, data)
du coup je repointe vers mon commentaire de la PR précédente. https://github.com/ToucanToco/toucan-connectors/pull/337#discussion_r587558811
J'ai l'impression qu'on fournit ici un une serie pandas qui correspond à la colonne 'properties' avec des données qui ne sont pas flattened dedans.

J'ai peut etre zappé un truc

2021-03-10 12:49 UTC, hachichaud commented on toucan_connectors/hubspot/hubspot_connector.py
> +            return format_hubspot_response(data_source.dataset, data)
dans le cas email_events, on aura bien un dataframe applati

2021-03-10 12:55 UTC, hachichaud commented on tests/hubspot/test_hubspot.py
> +
Pour tester que tu as bien une dataframe comme dans les email events, tu peux echanger : 

```suggestion
    assert df['eventType'][0] == 'party'
    assert df['occuredAt'][0] == '2021-03-08T12:28:40.305Z'

```

2021-03-10 12:57 UTC, hachichaud requested changes
Globalement, j'ai le meme commentaire sur le format de sortie que précédemment. 
Ca me semblerait plus judicieux de fournir directement les données au format tabulaire plutot que de forcer l'utilisateur à rajouter un flatten.

Ensuite j'ai mis des commentaires notamment sur les types de sortie des utiles et où mettre la définition de la class HubspotDataset.

2021-03-10 14:02 UTC, kadjou1 commented on toucan_connectors/hubspot/helpers.py
> +class HubspotDataset(str, Enum):
Fixé : https://github.com/ToucanToco/toucan-connectors/pull/340/commits/6259792ea6c600d683afbaeb40323e14eabd345c#diff-2d9fd6d3f67e299840f5b29b8b552da083390bc2722104d55dd3e58cd0e4f622

2021-03-10 14:03 UTC, kadjou1 commented on toucan_connectors/hubspot/helpers.py
> +def hubspot_api_format_v3(data: List[dict]) -> pd.DataFrame:
Fixé  : https://github.com/ToucanToco/toucan-connectors/pull/340/commits/f75b0319ab910501e34378b4a23036997c6a3853#diff-b0bbc03df068e102cbea31a2104a9b3044f4911ca41eb9fbd75a0ddd675b58faL8

2021-03-10 14:03 UTC, kadjou1 commented on toucan_connectors/hubspot/helpers.py
> +    For more information, look at the dedicated documentation: https://developers.hubspot.com/docs/api/events/web-analytics
Elle n'est pas legacy, c'était une mauvaise convention de nommage, fixé ici du coup : https://github.com/ToucanToco/toucan-connectors/pull/340/commits/f75b0319ab910501e34378b4a23036997c6a3853#diff-b0bbc03df068e102cbea31a2104a9b3044f4911ca41eb9fbd75a0ddd675b58faL78

2021-03-10 14:04 UTC, kadjou1 commented on tests/hubspot/test_hubspot.py
> +
Fixé ici : https://github.com/ToucanToco/toucan-connectors/commit/f75b0319ab910501e34378b4a23036997c6a3853#diff-890de93d94e4a0fa6918e0a3ff652f2c84a9b6ebe90eae80d354665a28c5ff3aL123-L124

2021-03-10 14:08 UTC, kadjou1 commented on toucan_connectors/hubspot/helpers.py
> +    stored under the properties, these formatting fuctions will extract these data
Fixé : https://github.com/ToucanToco/toucan-connectors/pull/340/commits/f75b0319ab910501e34378b4a23036997c6a3853#diff-b0bbc03df068e102cbea31a2104a9b3044f4911ca41eb9fbd75a0ddd675b58faR68

2021-03-10 15:37 UTC, hachichaud commented on toucan_connectors/hubspot/hubspot_connector.py
> +            return format_hubspot_response(data_source.dataset, data)
Ok, du coup les données intéressantes fournies dans la colonne properties ne sont pas exploitables par le front end / toucan lorsqu'elles sont au format json. Le format dictionnaire n'est pas vraiment utilisable tel quel.
Donc ce serait mieux d'aplatir les données.

2021-03-10 16:34 UTC, kadjou1 commented on toucan_connectors/hubspot/helpers.py
> +    return pd.DataFrame(data)['properties']
Souci fixé du coup, en utilisant une fonction pandas qui flatten les sous dictionnaires de la réponse : https://github.com/ToucanToco/toucan-connectors/pull/340/commits/668f40b633ea591293b303b153bcd3df7c5aa7f9

2021-03-10 16:34 UTC, kadjou1 commented on toucan_connectors/hubspot/hubspot_connector.py
> +            return format_hubspot_response(data_source.dataset, data)
Fixé ici : https://github.com/ToucanToco/toucan-connectors/pull/340/commits/668f40b633ea591293b303b153bcd3df7c5aa7f9

2021-03-10 16:38 UTC, kadjou1 commented on toucan_connectors/hubspot/helpers.py
> +    # Extract the useful data instead of returning everything contained in the event
On peut éventuellement partir du principe que c'est aux utilisateurs de filtrer les données à utiliser à la fin, vu qu'on peut flatten très facilement les données avec pandas au final.

WDYT @hachichaud ?

2021-03-10 16:57 UTC, kadjou1 commented on toucan_connectors/hubspot/helpers.py
> +    return df['properties']
Pour `format_hubspot_api_v3` les tests correspondent aux tests où le dataset n'a pas été modifié dans la datasource, ici principalement `test_hubspot_retrieve_data_pagination`

2021-03-10 17:38 UTC, raphaelvignes commented on toucan_connectors/hubspot/helpers.py
> +    # Extract the useful data instead of returning everything contained in the event
Oui, à la limite on peut laisser la flexibilité à l'utilisateur de parser lui même en fonction de ses besoins

2021-03-10 17:38 UTC, raphaelvignes commented on toucan_connectors/hubspot/helpers.py
> +    return pd.json_normalize(data)
:+1:

2021-03-11 08:47 UTC, hachichaud commented on toucan_connectors/hubspot/helpers.py
> +    # Extract the useful data instead of returning everything contained in the event
je trouve ca mieux de laisser les users filtrer eux mêmes. 
J'imagine un user qui lit la doc hubspot et ne comprend pas pourquoi une colonne ne remonte pas. 
Pour que le dataset soit le plus utilisable possible il faudrait donc renvoyer toutes les colonnes de manière aplatie.

2021-03-11 08:49 UTC, hachichaud commented on toucan_connectors/hubspot/hubspot_connector.py
> +            # versions.
Ce commentaire ne me semble pas forcément utile.
Si qqun se demande ce que fait cette méthode, la personne peut lire le docstring dans le fichier `helpers`
```suggestion
```

2021-03-11 08:54 UTC, hachichaud requested changes
Oui pour retourner toutes les données event.
Si je résume : 
On veut que les données ne soient plutot dans un format tabulaire. C'est ce genre de format que nos users savent manipuler et que le front consomme pour afficher des charts.
Autant que possible, il est préférable d'éviter une étape de transformation de data si on sait que nos utilisateurs vont le faire quoi qu'il arrive (typiquement le flatten des properties)

Pour les events, retourner ttes les données est aussi préférable pour éviter trop de différence entre les possibilités documentées sur Hubspot et notre implem.

2021-03-11 09:17 UTC, kadjou1 commented on toucan_connectors/hubspot/helpers.py
> +    # Extract the useful data instead of returning everything contained in the event
C'est changé [ici](https://github.com/ToucanToco/toucan-connectors/pull/340/commits/72751808c6521047c48e00f7cac1489cb33ebd4d)

2021-03-11 09:17 UTC, kadjou1 commented on toucan_connectors/hubspot/hubspot_connector.py
> +            # versions.
Vu que la gestion des données à changé, c'est fixé [ici](https://github.com/ToucanToco/toucan-connectors/pull/340/commits/72751808c6521047c48e00f7cac1489cb33ebd4d)

2021-03-11 14:13 UTC, hachichaud commented on toucan_connectors/hubspot/hubspot_connector.py
> +            return pd.json_normalize(data)
peut etre que plus tard on voudra donner un max_level histoire de pas prendre trop cher en perf si le nesting est grand

2021-03-11 14:14 UTC, hachichaud approved these changes

2021-03-11 16:25 UTC, merged