fix(snowflake): Use the expiration timestamp from the oauth token provided by the IDP
ToucanToco/toucan-connectors pull request #341
Opened 2021-03-08 15:26 UTC by kadjou1

## Change Summary

This commit fixes a previous behavior by reading the expiration timestamp from the decoded access_token instead of reading the
access_token from the oauth_args.

## Checklist

* [X] Unit tests for the changes exist
* [X] Tests pass on CI and coverage remains at 100%
* [ ] ~~Documentation reflects the changes where applicable~~

2021-03-08 15:27 UTC, kadjou1 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(8) ETQU Cegid (avec un token oauth), je n'ai pas besoin de me reloguer lorsque mon token oauth expire, il est rafraichit automatiquement](https://trello.com/c/gPrOPCHr/293-8-etqu-cegid-avec-un-token-oauth-je-nai-pas-besoin-de-me-reloguer-lorsque-mon-token-oauth-expire-il-est-rafraichit-automatiqueme)

2021-03-08 16:03 UTC, hachichaud commented
je crois que j'ai misclick et cliqué sur un element de la checklist dans la description , je suis pas sure 😅

2021-03-08 16:12 UTC, hachichaud commented on toucan_connectors/snowflake/snowflake_connector.py
> -                recieved_payload = res.json()
tu as quand meme besoin de mettre à jour le oauth_token avec la nouvelle valeur non ?

```
self.oauth_token = res.json().get('access_token')
```

?

2021-03-08 16:16 UTC, hachichaud commented on toucan_connectors/snowflake/snowflake_connector.py
> -                self.oauth_args['access_token'] = recieved_payload['access_token']
pense aussi à updater la doc https://github.com/ToucanToco/toucan-connectors/blob/master/doc/connectors/snowflake.md#L1:L1

2021-03-08 16:20 UTC, hachichaud requested changes
L'implem ne peut pas fonctionner en l'état car la requete de rafraichissement est bien faite, mais le résultat n'est pas utilisé.
Je suppose que les tests doivent louper pour ca. Si ce n'est pas le cas il faut ajouter un cas de test pour bien attraper ce genre d'erreur.
Il y a aussi la doc et les tests à mettre à jour avec les modifs oauth_args qui ont été faites : ne conserver que les oauth_args utilisés

2021-03-09 08:41 UTC, kadjou1 commented on toucan_connectors/snowflake/snowflake_connector.py
> -                recieved_payload = res.json()
Yep mais ça ne sera pas persisté en base par contre

2021-03-09 08:43 UTC, kadjou1 commented on toucan_connectors/snowflake/snowflake_connector.py
> -                recieved_payload = res.json()
J'ai re rajouté le statement du coup, pour le moment ça ne sert à rien mais dès qu'on persistera les infos en base après modification ça sera utile.

2021-03-09 08:44 UTC, kadjou1 commented on toucan_connectors/snowflake/snowflake_connector.py
> -                self.oauth_args['access_token'] = recieved_payload['access_token']
Yep, c'est fait.

2021-03-09 08:46 UTC, kadjou1 commented
> L'implem ne peut pas fonctionner en l'état car la requete de rafraichissement est bien faite, mais le résultat n'est pas utilisé.

Le souci c'est que tant qu'on ne persiste pas en base, les informations se feront écraser à chaque appel vers laputa pour récupérer les informations du connecteur.

>  Je suppose que les tests doivent louper pour ca. Si ce n'est pas le cas il faut ajouter un cas de test pour bien attraper ce genre d'erreur.

Les tests n'échouent pas, c'était sonarcloud qui n'était pas content à cause de l'introduction d'une vulnérabilité dans le code.

>  Il y a aussi la doc et les tests à mettre à jour avec les modifs oauth_args qui ont été faites : ne conserver que les oauth_args utilisés

C'est fait :slightly_smiling_face:

2021-03-09 10:55 UTC, hachichaud commented
@kadjou1 merci pour les changements.
Sur le point :

>Le souci c'est que tant qu'on ne persiste pas en base, les informations se feront écraser à chaque appel vers laputa pour récupérer les informations du connecteur.

C'est un souci qu'on a identifié, et qu'on a acté comme acceptable dans cette première implémentation.
C'est l'une des raisons pour laquelle on fait une PAT sur le mécanisme de refresh et la persistance en base.

La modif qui est faite ici ne sert pas à rien : ok on va refresh l' acces_token à chaque requete une fois que l'access token est expiré. Mais c'est mieux que de ne rien savoir rafraichir et de devoir se reloguer dès que l'acces token périme.

Pour rappel : durée de vie de l'access token : qques minutes, refresh token : qques heures.

En effet il faudra venir modifier le code lorsquon implémentera la PAT, mais _en attendant_ on produit la solution qui est dans cette PR et qui permet quand même d'améliorer les choses (et qui permet aussi de bien valider les différentes routes et échanges avec le client).

2021-03-09 10:59 UTC, hachichaud requested changes
Plus qu'un test à ajouter et c'est bon :)

2021-03-09 14:18 UTC, hachichaud commented
J'ai passé le point remonté par sonar sur le decode du jwt token en won't fix.
- le code en question est voué à disparaitre
- issue en cours de création

2021-03-09 14:20 UTC, hachichaud commented on tests/snowflake/test_snowflake.py
> +def test_oauth_refresh_token(mocker):
👍

2021-03-09 14:34 UTC, hachichaud approved these changes
👍

2021-03-09 14:37 UTC, merged