feat(snowflake): add role specification for snowflake connector
ToucanToco/toucan-connectors pull request #342
Opened 2021-03-08 15:42 UTC by kadjou1

## Change Summary

This PR adds the support of user defined [snowflake User Roles](https://docs.snowflake.com/en/user-guide/admin-user-management.html#user-roles).

## Checklist

* [X] Unit tests for the changes exist
* [X] Tests pass on CI and coverage remains at 100%
* [X] Documentation reflects the changes where applicable

2021-03-08 15:42 UTC, kadjou1 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(2) ETQConcepteur avec le connecteur Snowflake, je peux préciser un role dans les options du connecteur](https://trello.com/c/aETMZJvx/376-2-etqconcepteur-avec-le-connecteur-snowflake-je-peux-pr%C3%A9ciser-un-role-dans-les-options-du-connecteur)

2021-03-08 15:45 UTC, hachichaud commented on doc/connectors/snowflake.md
> +* `role`: str, optional: the [User Role] (https://docs.snowflake.com/en/user-guide/admin-user-management.html#user-roles) that your user may need to access certain data
```suggestion
* `role`: str, optional: the [User Role](https://docs.snowflake.com/en/user-guide/admin-user-management.html#user-roles) that your user may need to access certain data
```

2021-03-08 15:49 UTC, hachichaud commented on toucan_connectors/snowflake/snowflake_connector.py
> +        description='The user role that your account is eligible to. '
```suggestion
        description='The user role that you want to connect with'
```

2021-03-08 15:50 UTC, kadjou1 commented on doc/connectors/snowflake.md
> +* `role`: str, optional: the [User Role] (https://docs.snowflake.com/en/user-guide/admin-user-management.html#user-roles) that your user may need to access certain data
Fixé !

2021-03-08 15:51 UTC, kadjou1 commented on toucan_connectors/snowflake/snowflake_connector.py
> +        description='The user role that your account is eligible to. '
Fixé !

2021-03-08 15:54 UTC, hachichaud commented on toucan_connectors/snowflake/snowflake_connector.py
> +        if self.role != '':
je n'ai pas l'impression que tu testes ce cas dans les tests

2021-03-08 16:02 UTC, hachichaud requested changes
Pour moi il manque juste le cas de test pour role = ''

2021-03-09 14:47 UTC, kadjou1 commented on toucan_connectors/snowflake/snowflake_connector.py
> +        if self.role != '':
Yep, c'est ajouté ici du coup :

https://github.com/ToucanToco/toucan-connectors/pull/342/files#diff-95394a321d9013621f660895468f9af53a64e94e17ba0300ad4338117c0ac400R101-R110

2021-03-09 14:47 UTC, hachichaud approved these changes
👍

2021-03-09 14:55 UTC, merged