fix(snowflake): fix refresh mechanism and fix user management
ToucanToco/toucan-connectors pull request #343
Opened 2021-03-11 12:21 UTC by kadjou1

## Change Summary

This PR fixes two things : 

- The previous code used the original access_token even if a refresh occured
- The user used in case of a oauth authentication was not the one provided by the external IdP but the one that was saved in the connector at its creation; this PR makes the `sub` content supersede the `user` field if providen by the IdP

## Checklist

* [X] Unit tests for the changes exist
* [X] Tests pass on CI and coverage remains at 100%
* [ ] ~~Documentation reflects the changes where applicable~~

2021-03-11 12:25 UTC, kadjou1 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(8) ETQU Cegid (avec un token oauth), je n'ai pas besoin de me reloguer lorsque mon token oauth expire, il est rafraichit automatiquement](https://trello.com/c/gPrOPCHr/293-8-etqu-cegid-avec-un-token-oauth-je-nai-pas-besoin-de-me-reloguer-lorsque-mon-token-oauth-expire-il-est-rafraichit-automatiqueme)

2021-03-11 15:25 UTC, hachichaud commented on toucan_connectors/snowflake/snowflake_connector.py
> +                decoded = jwt.decode(
est-ce qu'on ne voudrait pas plutot garder le user s'il est défini dans la conf, et utiliser la valeur décodée si aucun user n'est fourni ?

2021-03-11 15:32 UTC, kadjou1 commented on toucan_connectors/snowflake/snowflake_connector.py
> +                decoded = jwt.decode(
Euh oui pourquoi pas, avec le recul ça me semble plus logique que la conf écrase les valeurs automatiques en effet.

2021-03-11 15:34 UTC, hachichaud commented on toucan_connectors/snowflake/snowflake_connector.py
> +                    res['user'] = decoded['sub']
En fait je ne comprends pas poruquoi on doit passer par là 'sub' ? Je pensais justement quon avait résolut le pb des scopes multiples et quon avait bien l'email et les infos nécessaires via la route /userinfo coté laputa.
On pourrait faire un `user: {{ useratributes['le username recupéré via userinfo'] }}`, non ?

2021-03-11 16:06 UTC, kadjou1 commented on toucan_connectors/snowflake/snowflake_connector.py
> +                decoded = jwt.decode(
Changé [ici](https://github.com/ToucanToco/toucan-connectors/pull/343/commits/727485cd20a1d66b83acb8a3790d61239ea1d5c9)

2021-03-11 16:07 UTC, kadjou1 commented on toucan_connectors/snowflake/snowflake_connector.py
> +                    res['user'] = decoded['sub']
En effet, j'ai rendu le user templatable dans [ce commit](https://github.com/ToucanToco/toucan-connectors/pull/343/commits/727485cd20a1d66b83acb8a3790d61239ea1d5c9)

2021-03-11 17:05 UTC, hachichaud commented on toucan_connectors/snowflake/snowflake_connector.py
> +                    res['user'] = decoded['sub']
on peut enlever la logique de sub non ?

2021-03-11 17:07 UTC, hachichaud requested changes
à mon avis on doit remettre le user en required et virer la logique de sub.
On n'en a plus besoin, et c'était spécifique au cas client

2021-03-12 09:34 UTC, kadjou1 commented on toucan_connectors/snowflake/snowflake_connector.py
> +                    res['user'] = decoded['sub']
Yep, c'est changé [ici](https://github.com/ToucanToco/toucan-connectors/pull/343/commits/9eb71f7b6743d2d7227920e301416c2ac9b15f29)

2021-03-12 09:34 UTC, kadjou1 commented
> à mon avis on doit remettre le user en required et virer la logique de sub.
> On n'en a plus besoin, et c'était spécifique au cas client

Yep, c'est changé dans [ce commit](https://github.com/ToucanToco/toucan-connectors/pull/343/commits/9eb71f7b6743d2d7227920e301416c2ac9b15f29) du coup.

2021-03-12 09:48 UTC, hachichaud commented on doc/connectors/snowflake.md
> +* `user`: str, optional: this username can be none if the connector is using a OIDC-based authentication
```suggestion
* `user`: str, required
```

2021-03-12 09:54 UTC, hachichaud requested changes
Il reste la doc à mettre à jour, sinon c'est bon 👍

2021-03-12 09:58 UTC, hachichaud approved these changes

2021-03-12 10:02 UTC, merged