refactor(http-api connector): update titles and descriptions for data…
ToucanToco/toucan-connectors pull request #361
Opened 2021-03-31 09:09 UTC by raphaelvignes

…source

## Change Summary

## Related issue number

## Checklist

* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%
* [ ] Documentation reflects the changes where applicable

2021-03-31 12:34 UTC, bloodstorms commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQC je vois des noms d'option + compréhensibles sur les champs du connecteur http (2) [3]](https://trello.com/c/8KoJWXc2/456-etqc-je-vois-des-noms-doption-compr%C3%A9hensibles-sur-les-champs-du-connecteur-http-2-3)

2021-03-31 15:00 UTC, hachichaud commented
@bloodstorms un test à maj https://github.com/ToucanToco/toucan-connectors/runs/2237712739

2021-03-31 15:01 UTC, hachichaud commented on toucan_connectors/http_api/http_api_connector.py
> +        description='you can also setup headers in the Template section of your Connector see: <br/>'
petite majuscule ?
```suggestion
        description='You can also setup headers in the Template section of your Connector see: <br/>'
```

2021-03-31 15:02 UTC, hachichaud commented on toucan_connectors/http_api/http_api_connector.py
> +        title='url param',
```suggestion
        title='URL params',
```

2021-03-31 15:02 UTC, hachichaud commented on toucan_connectors/http_api/http_api_connector.py
> +        title='body',
```suggestion
        title='Body',
```

2021-03-31 15:03 UTC, hachichaud requested changes
Un test à corriger et des majuscules ( je ne sais plus si le front capitalise les début de labels, mais dans le doute..)

2021-03-31 15:03 UTC, bloodstorms commented
> @bloodstorms un test à maj https://github.com/ToucanToco/toucan-connectors/runs/2237712739

Haha j'ai push la correction au moment même de ton commentaire :p

2021-03-31 15:04 UTC, bloodstorms commented
> Un test à corriger et des majuscules ( je ne sais plus si le front capitalise les début de labels, mais dans le doute..)

Pour les titres ils vont tous finir en cap lock sur le form builder, mais dans le doute je peux modifier :)

2021-03-31 15:06 UTC, bloodstorms commented on toucan_connectors/http_api/http_api_connector.py
> +        title='url param',
C'est au singulier dans la maquette par contre, quelle est la vraie version? <img width="574" alt="Screenshot 2021-03-31 at 17 06 19" src="https://user-images.githubusercontent.com/18734475/113166811-6af77b00-9243-11eb-9400-d23a98725b4c.png">

2021-03-31 17:30 UTC, bloodstorms commented
@raphaelvignes J'attends juste que @hachichaud me dise si c'est URL param ou URL param**s**

2021-04-01 07:05 UTC, raphaelvignes commented on toucan_connectors/http_api/http_api_connector.py
> +        title='url param',
Mettons URL Params, c'est plus logique.

2021-04-01 07:46 UTC, hachichaud commented on toucan_connectors/http_api/http_api_connector.py
> +        title='url param',
@bloodstorms oui je préfère params avec un S comme raph. Je pense que cest plus une typo dans la maquette miro qu'autre chose

2021-04-02 06:38 UTC, bloodstorms approved these changes

2021-04-02 07:09 UTC, hachichaud approved these changes

2021-04-02 07:13 UTC, merged