feat(snowflakeids connector): snowflake connector for ids
ToucanToco/toucan-connectors pull request #362
Opened 2021-04-06 20:05 UTC by raphaelvignes

## Change Summary

Creating a Snowflake connector for IDS use only.

## Checklist

* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%
* [ ] Documentation reflects the changes where applicable

2021-04-08 07:17 UTC, hachichaud commented
@raphaelvignes est-ce qu'on ne pourrait pas l'appeler SnowflakeOauth2Connector ? Ou est-ce qu'on est vraiment dans un cas d'utilisation propre aux IDS ? Ca pourrait être cool que le connecteur puisse aussi servir à d'autres que nous

2021-04-08 07:35 UTC, raphaelvignes commented
Oui, il pourra être utilisé en mode oAuth2 par tout le monde :+1:

2021-04-08 08:34 UTC, hachichaud requested changes
Je trouve ca dommage d'avoir autant de duplication de code. 
J'ai l'impression que ce qui change c'est surtout la gestion de la connection.
Dans le connecteur SnowflakeToutCourt on a aussi 2 logiques de connection qui cohabitent.
Est-ce qu'on ne pourrait pas factoriser les logiques de execute query, get warejouse, get databases ?

2e truc : `IDS` cest un terme interne. et ca correspond à un produit toucan. Je préfère quon renomme ce conncteur en SnowflakeOAuth2, ce sera plus compréhensible

2021-04-08 10:42 UTC, raphaelvignes commented
@hachichaud 
Si on fait tout dans un même connecteur alors il faut contourner la logique qui est déclenchée à cause de l'attribut de classe 
`
_auth_flow = 'oauth2'
`
Si le connecteur en question a cet attribut alors, l'ajout d'un connecteur Snowflake forcera l'ouverture de la pop-up de flow oAuth lors de l'ajout via "Add a connector".
Est-ce qu'on peut imaginer ajouter dynamiquement l'attribut de cette façon ?
`
if ids_app:
    setattr(snowflake_connector, '_auth_flow', 'oauth2')
`
Ok pour renommer le connecteur.

2021-04-08 18:59 UTC, raphaelvignes commented
Dans le dernier commit j'ai:
- supprimé le snowflakeids connector
- implémenté l'authentification oauth "flow user" dans le connecteur snowflake existant.

2021-04-12 13:29 UTC, hachichaud commented
@raphaelvignes j'ai pas compris pourquoi être revenu sur le fait de faire un connecteur séparé pour ce flow oAuth2 ?
J'ai l'impression que du coup ca rajoute pas mal de complexité et de spécificité à des endroits où on n'a pas forcément envie (ex dans le code générique connector)
En fusionnant les 2, j'ai l'impression qu'on rajoute du `if snowflake` dans tucana, dans les connectors, dans laputa.
Est-ce quon peut se prendre un moment pour réfléchir à une solution propre ?

2021-04-12 13:36 UTC, raphaelvignes commented
Yup, dispo pour revoir ça. 
Donc l'idée serait plutôt de faire une classe SnowflakeoAuth2Connector qui hériterait de celle-ci ?

2021-05-11 07:14 UTC, closed without merging