Query Pool experience
ToucanToco/toucan-connectors pull request #443
Opened 2021-06-29 15:51 UTC by f-bb-toucantoco

## Change Summary

Implement a ConnectionManager to keep open connection
All connections are stored in an object created at the root of the connector

`connection_manager = None
if not connection_manager:
    connection_manager = ConnectionManager(
        name='snowflake',
        timeout=20,
        wait=0.2,
        time_between_clean=10,
        time_keep_alive=600
    )
`
- timeout : Recover a connection with the timeout, if the timeout is exceeded, an exception is generated
- wait: time between 2 check to recover the connection
- time_between_clean: time between 2 laps to check if a connections needs to be removed
- time_keep_alive: time to keep the connection open

To retrieve (or create) the connection: 
`        connection = connection_manager.get(
            self.identifier,
            connect_method=lambda: connect_function(database, warehouse),
            alive_method=lambda: alive_function(),
            close_method=lambda: close_function(),
        )`

- connection_method: a method in your connector to connect at the external service
- alive_method: a method to return True or False status for the connection
- close_method: a method to close the connection at the external service

For more information about the implementation, you could check snowflake_connector.py or snowflake_oauth2_connector.py

## Change summary 2

Merge get data method in new Class for snowflake_connector.py and snowflake_oauth2_connector.py
The goals for this merge is to have only one place for Business Intelligence

## Checklist

* [X] Unit tests for the changes exist
* [X] Tests pass on CI and coverage remains at 100%
* [ ] Documentation reflects the changes where applicable

2021-06-30 14:54 UTC, f-bb-toucantoco commented
Désolé pour la taille, il y a eu pas mal de changement en cours de route
@piotch Pour la documentation d'implémentation elle sera faite soit sur ce Sprint, soit sur le suivant

2021-06-30 14:55 UTC, f-bb-toucantoco commented
![](https://github.trello.services/images/mini-trello-icon.png) [(2) [SF Query Performance - 2] - Complete Unit test for connection_manager](https://trello.com/c/WZUv1iwu/1007-2-sf-query-performance-2-complete-unit-test-for-connectionmanager)

2021-07-01 07:14 UTC, raphaelvignes commented on tests/test_connection_manager.py
> +    assert len(connection_manager.cm) == 1
Comment est ce qu'on ferme la connexion si pas de méthode  définie pour le faire ?

2021-07-01 07:15 UTC, raphaelvignes commented on tests/test_connection_manager.py
> +    _get_connection_without_connect_method(connection_manager, 'conn_1')
Dans ce cas il y' a une exception qui est levée quelque part ?

2021-07-01 11:58 UTC, raphaelvignes commented on toucan_connectors/connection_manager.py
> +
Est-ce que ces params seront configurables/customizable quelque part ?

2021-07-01 12:21 UTC, raphaelvignes commented on toucan_connectors/connection_manager.py
> +            logger.debug('Connection not exist, create and save it')
```suggestion
            logger.debug('Connection does not exist, create and save it')

```

2021-07-01 12:22 UTC, raphaelvignes commented on toucan_connectors/connection_manager.py
> +        self.cm[key]['status'] = 'is_closing'
Est ce qu'on devrait utiliser une enum pour les status ?

2021-07-01 12:27 UTC, raphaelvignes commented on toucan_connectors/snowflake_common.py
> +            warehouse['name'] for warehouse in self._execute_query(c, query) if 'name' in warehouse
`_execute_query` renvoie un DataFrame, du coup je suggère ceci: 

```suggestion
        res = self._execute_query(c, query).to_dict().get('name')
        return [warehouse for warehouse in res.values()] if res else []
```

2021-07-01 12:28 UTC, raphaelvignes commented on toucan_connectors/snowflake_common.py
> +            database['name'] for database in self._execute_query(c, query) if 'name' in database
Idem ici 

```suggestion
        res = self._execute_query(c, query).to_dict().get('name')
        return [database for database in res.values()] if res else []
```

2021-07-01 12:30 UTC, raphaelvignes commented on toucan_connectors/snowflake_oauth2/snowflake_oauth2_connector.py
> +        name='snowflake_oauth2', timeout=5, wait=0.2, time_between_clean=3, time_keep_alive=600
Faudrait que ces params soient configurables non ?

2021-07-01 12:32 UTC, raphaelvignes commented on toucan_connectors/snowflake_oauth2/snowflake_oauth2_connector.py
>          )
On passe une lambda ou directement la référence de la méthode ? 
```suggestion
            connect_method=connect_function,
            alive_method=alive_function,
            close_method=close_function,
```

2021-07-01 12:32 UTC, raphaelvignes commented on toucan_connectors/snowflake_oauth2/snowflake_oauth2_connector.py
> +            close_method=lambda: close_function(),
On passe une lambda ou directement la référence de la méthode ? 
```suggestion
            connect_method=connect_function,
            alive_method=alive_function,
            close_method=close_function,
```

2021-07-01 12:34 UTC, raphaelvignes commented on toucan_connectors/snowflake_oauth2/snowflake_oauth2_connector.py
> +        permissions: Optional[dict] = None,
On en fait quoi permissions ?

2021-07-01 12:34 UTC, raphaelvignes commented on toucan_connectors/toucan_connector.py
> +    # Use to defined the connection
```suggestion
    # Used to define the connection
```

2021-07-01 12:35 UTC, raphaelvignes reviewed
J'ai fais une passe. 
Mais il faudra une revue avec un regard plus avisé que le mien !

2021-07-05 10:03 UTC, piotch commented on tests/snowflake/test_snowflake.py
> +data = {
this could be in a fixture file

2021-07-05 10:03 UTC, piotch commented on tests/snowflake/test_snowflake.py
> +def test_datasource_get_databases(gd, gc, snowflake_connector, snowflake_datasource):
are you not just testing the mock here ?

2021-07-05 10:11 UTC, piotch commented on toucan_connectors/connection_manager.py
> +        self.__dict__.update(kwargs)
this is valid syntax but what would you expect that it does ?

2021-07-05 10:12 UTC, piotch commented on toucan_connectors/connection_manager.py
> +class ConnectionObject:
naming : `ConnectionObject` because of the Object type I guess? but Object is really wide term in python, can we narrow this down ?

2021-07-05 10:15 UTC, piotch commented on toucan_connectors/connection_manager.py
> +    def __close(self, key):
I don't understant the naming convention `__` vs. `_`

2021-07-05 10:19 UTC, piotch commented on toucan_connectors/snowflake/snowflake_connector.py
> +        def connect_function(
do we need a nested function here ?

2021-07-05 10:20 UTC, piotch commented on toucan_connectors/snowflake/snowflake_connector.py
> +            close_method=lambda: close_function(),
I don't understand why we need a lambda here

2021-07-05 10:21 UTC, piotch commented on toucan_connectors/snowflake/snowflake_connector.py
> +            if result.__len__() != 1:
```suggestion
            if len(result) != 1:
```

2021-07-05 10:24 UTC, piotch commented on toucan_connectors/snowflake_common.py
> +        c,
single letter variable, no annotation

2021-07-05 10:28 UTC, piotch requested changes
I spotted some details points but more generally my main point would be that we need a high level doc that describes how this works. From there I can do a more complete review.

2021-07-07 21:08 UTC, piotch commented on doc/connection_manager.md
> +ConnectionManager is a Class to store and maintain the connection at a provider between 2 requests on the same worker
```suggestion
ConnectionManager is a Class to store and maintain connections to a data provider, outliving the request response cycle at a single worker level.
```

2021-07-07 21:09 UTC, piotch commented on doc/connection_manager.md
> +In the **gunicorn** workflow, when we received a request, we create the connection, use it and destroy it
```suggestion
In the previous workflow, when we received a live data request, we created a connection, used it once and immediately closed it.
```

2021-07-07 21:10 UTC, piotch commented on doc/connection_manager.md
> +With this workflow, when we received a request, we ask a connection, create it if not exist, use it
```suggestion
With this workflow, when we received a request, we ask a connection, create it if not exist, use it but then it is kept live for further requests.
```

2021-07-07 21:12 UTC, piotch commented on doc/connection_manager.md
> +The clean of connection runs in parallel and close after check if the connection is :
```suggestion
There is a thread that cleans ConnectionManager and closes connections after checking  first : 
```

2021-07-07 21:12 UTC, piotch commented on doc/connection_manager.md
> +- alive
```suggestion
- whether it is alive
```

2021-07-07 21:12 UTC, piotch commented on doc/connection_manager.md
> +- has been used since X times
```suggestion
- if has been used since X times
```

2021-07-07 21:13 UTC, piotch commented on doc/connection_manager.md
> +Method __connect, __alive and __cancel are
pb de copier coller ?

2021-07-07 21:13 UTC, piotch commented on doc/connection_manager.md
> +To have more information about the process, you can refer at this [Confluence Documentation](https://toucantoco.atlassian.net/wiki/spaces/TTA/pages/3018653948/Connection+Manager+-+Query+pool?focusedC
```suggestion
For more information about the process, you can refer at this [Confluence Documentation](https://toucantoco.atlassian.net/wiki/spaces/TTA/pages/3018653948/Connection+Manager+-+Query+pool?focusedCommentId=3021308042#comment-3021308042)
```

2021-07-07 21:16 UTC, piotch commented on toucan_connectors/connection_manager.py
> +    def force_to_remove(self):
```suggestion
    def force_to_remove(self):
        """Return True when closing or if check alive raises Exception 3 times."""
```

2021-07-07 21:44 UTC, piotch commented on toucan_connectors/connection_manager.py
> +    def __remove(self, list_connection_to_remove):
La convention en python est plutôt : 

- `_private_method`
- `__magic_method__`

2021-07-08 05:53 UTC, piotch commented on toucan_connectors/connection_manager.py
> +    def __get_wait(
```suggestion
    def __get_wait(
        """Retrieve connection when the connection as Status.AVAILABLE or Status.QUERY_IN_PROGRESS"""
```

2021-07-08 05:54 UTC, piotch commented on toucan_connectors/connection_manager.py
> +    def get(self, identifier: str, connect_method, alive_method, close_method):
```suggestion
    def get(self, identifier: str, connect_method, alive_method, close_method):
        """Retrieve or create connection if not exist in connection_list"""
```

2021-07-08 05:54 UTC, piotch commented on toucan_connectors/connection_manager.py
> +    def force_clean(self):
```suggestion
    def force_clean(self):
        """
        Force to remove all connection
        Not use automatically by connection_manager
        """
```

2021-07-08 05:55 UTC, piotch approved these changes

2021-07-21 14:34 UTC, merged