feat(spotify): add spotify connector
ToucanToco/toucan-connectors pull request #462
Opened 2021-07-29 12:17 UTC by Sanix-Darker

![Screenshot from 2021-07-29 13-57-50](https://user-images.githubusercontent.com/22576758/127490140-5a8bbb8d-7d9d-48cb-8ca2-087e9ea0c88e.png)

## Change Summary
Just added `Spotify` connector while reading and learning how toucan-connectors works...

## Related issue number
N/A

## Checklist

* [x] Unit tests for the changes exist
* [x] Tests pass on CI and coverage remains at 100%
* [x] Documentation reflects the changes where applicable

2021-07-29 12:51 UTC, f-bb-toucantoco requested changes

2021-07-29 12:51 UTC, f-bb-toucantoco commented on doc/connectors.md
> +* [OdbcConnector](connectors/odbc.md)
???

2021-07-29 12:51 UTC, f-bb-toucantoco commented on doc/connectors.md
> +* [RokConnector](connectors/rok.md)
???

2021-07-29 12:51 UTC, f-bb-toucantoco commented on toucan_connectors/spotify/spotify_connector.py
> +    global spotify_connection
Est-ce que tu es sûr que c'est une bonne idée ?

2021-07-29 12:51 UTC, f-bb-toucantoco commented on toucan_connectors/spotify/spotify_connector.py
> +    domain: str = Field(
Peut-être que tu peux ajouter un élément de placeholder (cf snowflale connector)

2021-07-29 12:51 UTC, f-bb-toucantoco commented on toucan_connectors/spotify/spotify_connector.py
> +        description='Spotify Name',
Peut-être que tu peux ajouter un élément de placeholder (cf snowflale connector)

2021-07-29 12:51 UTC, f-bb-toucantoco commented on toucan_connectors/spotify/spotify_connector.py
> +    name: str = Field(
Est-ce que ça fait partie de ta source de données ? ou est-ce que ça fait partie des paramètres de connexion ?

2021-07-29 12:51 UTC, f-bb-toucantoco commented on toucan_connectors/spotify/spotify_connector.py
> +    domain: str = Field(
Est-ce que ça fait partie de ta source de données ? ou est-ce que ça fait partie des paramètres de connexion ?

2021-07-29 12:51 UTC, f-bb-toucantoco commented on toucan_connectors/spotify/spotify_connector.py
> +    domain: str = Field(
est-ce que ce champs peut être différent ou c'est toujours spotify.com, peut-être pas nécessaire d'en faire un champs

2021-07-29 12:51 UTC, f-bb-toucantoco commented on toucan_connectors/spotify/spotify_connector.py
> +    query: str = Field(
Est-ce que ça fait partie de ta source de données ? ou est-ce que ça fait partie des paramètres de connexion ?

2021-07-29 12:51 UTC, f-bb-toucantoco commented on toucan_connectors/spotify/spotify_connector.py
> +    limit: int = Field(
Est-ce que ça fait partie de ta source de données ? ou est-ce que ça fait partie des paramètres de connexion ?

2021-07-29 12:54 UTC, Sanix-Darker commented on doc/connectors.md
> +* [OdbcConnector](connectors/odbc.md)
Je vais probablement retirer ce fichier de cette PR, car plein de choses y ont ete fait generiquement, je ne l'ai pas update en personne !

2021-07-29 12:54 UTC, Sanix-Darker commented on doc/connectors.md
> +* [RokConnector](connectors/rok.md)
same

2021-07-29 12:57 UTC, Sanix-Darker commented on toucan_connectors/spotify/spotify_connector.py
> +    global spotify_connection
Si plusieurs calls se font, je me suis dit que ce serait interessant de conserver pour chaque call le meme objet, mais avec du recul, je dois aussi check que les credentials changent ou pas ? :thinking: 
Par `bonne idée`, peux tu etre un peu plus explicite stp ?

2021-07-29 13:06 UTC, Sanix-Darker commented on toucan_connectors/spotify/spotify_connector.py
> +    query: str = Field(
De la source de données !
Exemple : "daft punk"

2021-07-29 13:06 UTC, Sanix-Darker commented on toucan_connectors/spotify/spotify_connector.py
> +    limit: int = Field(
De la source de données !
Exemple : 10

2021-07-29 13:37 UTC, raphaelvignes requested changes
Merci pour ce nouveau connecteur ! 
Je comprends qu'il s'agit d'un connecteur qui marche en oauth. 
Du coup tu devrais pouvoir l'adapter sur le modèle du connecteur SnowflakeOauth2 pour permettre à un utilisateur de s'authentifier via une pop up oauth2.

2021-07-29 13:37 UTC, raphaelvignes commented on toucan_connectors/spotify/spotify_connector.py
> +def get_spotipy_connect(client_id, client_secret):
Tu peux rajouter le type de retour stp ?

2021-07-29 13:37 UTC, raphaelvignes commented on toucan_connectors/spotify/spotify_connector.py
> +
On ne met plus `client_id` et `client_secret` dans la config de la data source. Si ton connecteur est un connecteur oauth, il doit implémenter la même logique que ce qu'il y'a dans SnowflakeOAuth2 connector (par exemple).

2021-08-02 01:09 UTC, Sanix-Darker commented on toucan_connectors/spotify/spotify_connector.py
> +def get_spotipy_connect(client_id, client_secret):
done !

2021-08-02 01:09 UTC, Sanix-Darker commented on toucan_connectors/spotify/spotify_connector.py
> +
done !

2021-08-02 01:11 UTC, Sanix-Darker commented on toucan_connectors/spotify/spotify_connector.py
> +        description='Spotify Name',
done !

2021-08-10 13:36 UTC, f-bb-toucantoco requested changes

2021-08-10 13:36 UTC, f-bb-toucantoco commented on toucan_connectors/spotify/spotify_connector.py
> +    ui_hidden = {'ui.hidden': True}
un petit peu lourd de le mettre en haut comme ça, je pense que ça reste mieux si c'est présent dans les Field directement

2021-08-10 13:36 UTC, f-bb-toucantoco commented on toucan_connectors/spotify/spotify_connector.py
> +        self.authorization_url = 'https://accounts.spotify.com/authorize'
Pourquoi mettre sa valeur ici alors qu'il y a un **Field** un peu plus haut dans lequel tu peux mettre sa valeur par défaut

2021-08-10 13:36 UTC, f-bb-toucantoco commented on toucan_connectors/spotify/spotify_connector.py
> +        self.token_url = 'https://accounts.spotify.com/api/token'
Pourquoi mettre sa valeur ici alors qu'il y a un **Field** un peu plus haut dans lequel tu peux mettre sa valeur par défaut

2021-08-10 13:36 UTC, f-bb-toucantoco commented on toucan_connectors/spotify/spotify_connector.py
> +            redirect_uri=self.redirect_uri,
Le **Field** est caché mais tu utilise la variable non définie, je ne pense pas que ça puisse marcher de cette façon

2021-08-10 13:36 UTC, f-bb-toucantoco commented on toucan_connectors/spotify/spotify_connector.py
> +            secrets_keeper=kwargs['secrets_keeper'],
un check sur le fait que **kwargs['secrets_keeper']** existe bien serait pas mal

2021-08-10 13:36 UTC, f-bb-toucantoco commented on toucan_connectors/spotify/spotify_connector.py
> +        return SpotifyOAuth(
Un log pour dire que la connexion se fait et un log pour dire que la connexion a réussi ou échoué serait pas mal (attention au niveau de log, il faut en mettre, mais au bon level en fonction de l'intérêt)
Côté log tu peux regarder ce qui est fait côté SnowflakeConnector pour reprendre le même principe et ajouter des informations de durée

2021-08-10 13:36 UTC, f-bb-toucantoco commented on toucan_connectors/spotify/spotify_connector.py
> +            Spotify(auth_manager=self.connect()).search(
Un log pour dire que la requête va être joué avec tels arguments serait pas mal (attention au niveau de log, il faut en mettre, mais au bon level en fonction de l'intérêt), de même dans le cas où la requête a échoué 
Côté log tu peux regarder ce qui est fait côté SnowflakeConnector pour reprendre le même principe et ajouter des informations de durée

2021-08-19 19:22 UTC, closed without merging

2021-08-20 06:42 UTC, f-bb-toucantoco commented
Why you close your PR on this connector?