fix: bigQuery variables interpolation [TCTC-3642]
ToucanToco/toucan-connectors pull request #669
Opened 2022-09-13 06:59 UTC by Sanix-Darker

## WHAT

It seems like, when a give variable has a space between '@' and its keys
name '__front_var_0__', it's impossible for bigquery to set well that
variable, since it's based on `str.find` as for an example :

```python
>>> query = 'SELECT @ __front_var_0__';
>>> query.find('@' + '__front_var_0');
-1
>>> query.find('@ ' + '__front_var_0__');
12
```

## Change Summary

## Related issue number

## Checklist

* [ ] Unit tests for the changes exist
* [ ] Tests pass on CI and coverage remains at 100%
* [ ] Documentation reflects the changes where applicable

2022-09-13 07:57 UTC, jGundermann requested changes

2022-09-13 07:57 UTC, jGundermann commented on toucan_connectors/google_big_query/google_big_query_connector.py
> +        )
There is a helper function for the interpolation named : sanitize_query.
You can have a example here 
https://github.com/ToucanToco/toucan-connectors/blob/master/toucan_connectors/awsathena/awsathena_connector.py#L58

2022-09-13 09:03 UTC, jGundermann approved these changes
LGTM

2022-09-14 10:27 UTC, Sanix-Darker commented
So this should be renamed as "feat: bigQuery, add no injection SQL to interpolated variables"

2022-09-14 13:51 UTC, Sanix-Darker commented
Confirmed that it's now working, so, i can merge it !
Thanks for the review @jGundermann

2022-09-14 13:51 UTC, merged