feat: allow empty field mysql ssl [TCTC-5306]
ToucanToco/toucan-connectors pull request #938
Opened 2023-02-20 13:08 UTC by Sanix-Darker

## WHAT

we want to have ssl_ca, ssl_cert and ssl_key as optional params for an ssl connexion

2023-02-20 14:35 UTC, lukapeschke requested changes

2023-02-20 14:35 UTC, lukapeschke commented on toucan_connectors/mysql/mysql_connector.py
> +                    },
This beahviour is not valid: We only want to check if the hostname matches the cert if the mode is VERIFY_IDENTITY

2023-02-20 14:35 UTC, lukapeschke commented on toucan_connectors/mysql/mysql_connector.py
> +                if ssl_opt in ssl_params:
```suggestion
                if ssl_opt in ssl_params:
                    ssl_opt_file = NamedTemporaryFile(prefix=ssl_opt)
```

2023-02-20 14:35 UTC, lukapeschke commented on toucan_connectors/mysql/mysql_connector.py
> +                    ), f'SSL option {k} should be available if {p} is provided !'
```suggestion
                    ), f'SSL option {k} should be specified if {p} is provided !'
```

2023-02-20 14:35 UTC, lukapeschke commented on toucan_connectors/mysql/mysql_connector.py
> +                    connection_params |= {**connection_params, **{ssl_opt: ssl_opt_type.name}}
```suggestion
                    connection_params[ssl_opt] = ssl_opt_file.name
```

2023-02-20 14:35 UTC, lukapeschke commented on toucan_connectors/mysql/mysql_connector.py
> +            for k, p in (('ssl_key', 'ssl_cert'), ('ssl_cert', 'ssl_key')):
Sure, why not

2023-02-20 15:54 UTC, lukapeschke reviewed
A few inline comments. Also, have you been able to test this on a mysql server with mandatory SSL ?

2023-02-20 15:54 UTC, lukapeschke commented on tests/mysql/test_mysql.py
> -    assert kwargs['ssl_key'] is not None
Same remark here

2023-02-20 15:54 UTC, lukapeschke commented on toucan_connectors/mysql/mysql_connector.py
>                  }
This should be outside of the loop:

```python
connection_params["ssl_verify_identity"] = self.ssl_mode == SSLMode.VERIFY_IDENTITY}
```

2023-02-20 16:00 UTC, Sanix-Darker commented on toucan_connectors/mysql/mysql_connector.py
>                  }
🤦🏽‍♂️

2023-02-21 20:47 UTC, Sanix-Darker commented
Tested on a local stack:

- With CA certificate only GOOD/BAD (cred)
  - On a good/valid CA.pem:

![Screenshot from 2023-02-21 21-14-10](https://user-images.githubusercontent.com/22576758/220454341-18fcdaa5-07de-4c74-b7da-967994b54f81.png)
  - On a Bad CA.pem:
  
![Screenshot from 2023-02-21 21-15-10](https://user-images.githubusercontent.com/22576758/220454390-01049bcf-c9ff-491b-a3a6-0b934a9b0013.png)

- With Cert/Key one missing, we raise the appropriate validation error
![Screenshot from 2023-02-21 20-33-53](https://user-images.githubusercontent.com/22576758/220454550-2380f595-9af0-4c88-b07f-49210255c73c.png)

2023-02-22 09:09 UTC, lukapeschke approved these changes

2023-02-22 11:41 UTC, merged